- Modules/Preview/VixenPreview/PreviewCustomPropBuilder.cs
Added logic to assign a generic name of "Unnamed" to any elements that do not have a name. Need to raise another ticket to prevent the prop editor from allowing empty names.
> VIX-2739 Fix crash when an element on an imported prop is blank.

- Modules/Effect/LipSync/LipSync.cs
The logic will look for the first collection that is designated as a Phoneme and select it automatically if there is not a collection already set. This will save some step to selecting something that will initially work.
> VIX-2537 Add logic to select a reasonable Mark collection.

- Modules/App/CustomPropEditor/CustomPropEditor.csproj
- Modules/Editor/EffectEditor/EffectEditor.csproj
The System.Windows.Interactivity was being copied local in the effect editor and that caused a localization conflict between two loaded versions. This corrects the copy local issue and solves the crash.
I also found a few items in the Custom Prop Editor that were copying local when they should not be. I don;t think these were causing any immediate issues, but I cleaned them up to be sure.
> VIX-2781 Fix hard crash when loading dependencies.

- Common/WPFCommon/Theme/Theme.xaml
- Modules/App/CustomPropEditor/CustomPropEditor.csproj
- Modules/App/CustomPropEditor/Import/XLights/FaceInfo.cs
- Modules/App/CustomPropEditor/Import/XLights/SubModel.cs
- Modules/App/CustomPropEditor/Import/XLights/XModelImport.cs
- Modules/App/CustomPropEditor/Model/ElementModel.cs
- Modules/App/CustomPropEditor/Model/FaceComponent.cs
- Modules/App/CustomPropEditor/Services/PropModelServices.cs
- Modules/App/CustomPropEditor/ViewModels/ElementModelViewModel.cs
- Modules/App/CustomPropEditor/Views/CustomPropEditorWindow.xaml
- Modules/Preview/VixenPreview/PreviewCustomPropBuilder.cs
- Modules/Preview/VixenPreview/VixenPreview.csproj
- Modules/Preview/VixenPreview/VixenPreviewSetupElementsDocument.cs
Added a tab to manage Element properties into the prop editor. Separated the general prop info from a Element info tab. This tab provides the ability to see more details on the Element. Added a Face Component property to Elements and gave the ability for the user to assign a face component to an element or most likely group.
Added the ability to map the new Face Component property on the model to the Face Property upon loading a prop into the preview. This sets up the mapping according to the model definition.
Added the ability to import the xModel face definitions and map them to the new Face Component when importing a model. Now if the model is setup correctly the user will have very little additional work to do. They can alter that mapping with the mechanism above in the prop editor to …
> VIX-2789 Add support for Face Mapping in the Custom Prop Editor.

- Vixen.System/Data/Value/DiscreteValue.cs
- Vixen.System/Data/Value/LightingValue.cs
- Vixen.System/Intent/StaticDiscreteLightingIntent.cs
- Vixen.System/Intent/StaticLightingIntent.cs
- Vixen.System/Interpolator/StaticDiscreteValueInterpolator.cs
- Vixen.System/Interpolator/StaticLightingValueInterpolator.cs
- Vixen.System/Vixen.csproj
The Set Level was changed to use a static intent instead of interpolating, but it needs a minimal interpolator that returns a copy of the value so that i tcan be modified downstream. Create interpolators for the discrete and lighting value types that return a copy of the value as the point in time intent.
> VIX-2792 Fix an issue in the where the set level effect fails to work.

- Modules/App/Shows/Actions/Action.cs
- Modules/App/Shows/Actions/SequenceAction.cs
- Modules/App/Shows/SequenceManager.cs
- Modules/App/Shows/ShowEditorForm.cs
- Vixen.System/Module/Effect/EffectModuleInstanceBase.cs
- Vixen.System/Module/Effect/IEffect.cs
Rework the logic around the SequenceManager and the SequenceAction to be able to detect if a sequence changes while the show is running. If so reload the new version and retire the old one. This may have render impact on the running show, but I assume the user takes that knowledge when they want to change it.
Add logic to detect render errors in the SequenceAction and mark the item as can't execute so it will bypass it instead of throwing logs full of errors. IF the user fixes and saves as above, then it can run when it comes around if it renders properly.
> VIX-2693 Improve some aspects of the scheduler.

- Common/Controls/MultiSelectTreeview.cs
- Modules/Preview/VixenPreview/Shapes/DisplayItemBaseControl.cs
- Modules/Preview/VixenPreview/Shapes/PreviewShapeBaseSetupControl.cs
- Modules/Preview/VixenPreview/VixenPreviewControl.Designer.cs
- Modules/Preview/VixenPreview/VixenPreviewControl.cs
- Modules/Preview/VixenPreview/VixenPreviewSetup3.cs
- Modules/Preview/VixenPreview/VixenPreviewSetupDocument.Designer.cs
- Modules/Preview/VixenPreview/VixenPreviewSetupDocument.cs
- Modules/Preview/VixenPreview/VixenPreviewSetupDocument.resx
- Modules/Preview/VixenPreview/VixenPreviewSetupElementsDocument.cs
- Modules/Preview/VixenPreview/VixenPreviewSetupPropertiesDocument.cs
Remove the render timer that rendered all the time on a schedule. Add logic to all the places that change things that affect the display to call the render routine and update the screen. This reduces render cycles to those that are actually needed to respond to changes. This significantly reduces the amount of CPU used in this form. As we allowing more setup in this screen, users will be spending more time in it and the improvement will be much needed.
> VIX-2819 Improve the performance of the Preview Setup screen.

- Modules/Effect/Video/Video.cs
The index checking was not being handled correctly and could let invalid values pass through. This should prevent that, but not sure why the values where out of bounds to start with as I cannot recreate the users original problem.
> VIX-2808 Fix an index out of bounds exception in the video effect.

- Common/Controls/MultiSelectTreeview.cs
- Modules/Preview/VixenPreview/Shapes/PreviewSetElements.cs
Restructure the logic that sorts the columns in the preview elements linking to only adjust the columns once the operation has been completed.
Refactor the drag logic to be more efficient in how it selects the hovered target. Fix the drag enter and drag over methods to work correctly and set the proper effect when the element can be dropped and when it can't. This should eliminate the bizarre popup when it is dropped in the wrong place.
Make an optimization in the Element tree sorting mechanism to allow it to sort faster when elements have the same parent. This can speed up element selection a fair amount. Further optimization could be done later with more extensive refactoring.
> VIX-2820 Optimize the linking in the preview setup.

- Common/Controls/TimeLineControl/Row.cs
The editor was drawing the row layout after every row was added to the time line even when they are not visible. Refactor to only fire the event for visible rows so it does not do unnecessary changes.
> VIX-2821 Optimize the row loading in the editor.

- Modules/App/TimedSequenceMapper/SequencePackageExport/SequencePackageExportSummaryStage.cs
- Modules/App/TimedSequenceMapper/SequencePackageImport/SequencePackageImportSummaryStage.cs
Add logic to handle the Nutcracker files on export. Even though they are deprecated there are likely still some in the wild.
Add additional error handling to manage issues with the export. Add logic to provide messaging to the user when errors occur.
Clean up some leftover commented code.
> VIX-2826 Various fixes and polish.

- Modules/Editor/TimedSequenceEditor/Forms/WPF/MarksDocker/ViewModels/MarkCollectionViewModel.cs
The model binding was using the concrete type vs the interface which was throwing a binding warning.
> VIX-2834 Find binding warning in the Mark Collection editor.

- Common/Controls/TimeLineControl/Grid.cs
- Common/Controls/TimeLineControl/Grid_Mouse.cs
The fix in a previous ticket did not solve for multiple effects overlapping on the same element row. This takes into account the stacking logic to resolve that and still maintain the function when the same row is exposed multiple times.
Add logic to ignore the CAD style selection logic so the Shift select can use it without changing behaviors depending on the direction of the rectangle.
> VIX-2841 Fix a few bugs in the select within logic.

- Common/Controls/ElementTree.cs
- Modules/Preview/VixenPreview/Shapes/PreviewSetElements.cs
- Modules/Preview/VixenPreview/Shapes/PreviewTools.cs
The ticket was focused on the speed of selection. There is not any logic around the treeview selection, so the speed is purely the cost of the control itself managing the selection. Virtualizing the tree makes it smaller, so it will load faster and maybe the selection logic will work better with a smaller foot print.
Fix a double cast in the expand logic in the setup element tree that was found when reusing the logic for this fix. Marginal improvement, but proper structure.
> VIX-2840 Virtualize the link elements tree loading in the Preview.

- Modules/Editor/TimedSequenceEditor/TimedSequenceEditorForm.cs
Fix the validation logic in the paste method to return if the proper data is not retrieved from the the clipboard.
> VIX-2872 Paste of non supported data crashes Vixen.

- Modules/Effect/SetLevel/SetLevel.cs
When a Set Level is used on a group of discrete elements and a dimming curve is in place, those multiple elements will have a multiplier of the dimming curve for each child under the main group. The fix is to ensure each child element gets it's own intent vs trying to share a common one across them.
> VIX-2792 Part two of this fix to address additional issues.

- Modules/Preview/VixenPreview/VixenPreviewSetup3.cs
The previous refactor that changed the preview rendering to on demand needs to have specific refresh calls to render when things change. Added the calls when the undo redo is executed.
> VIX-2851 Fix refresh issue on undo redo items in the preview.

- Common/Libraries/Libraries.csproj
- Modules/App/Curves/CurveEditor.cs
- Modules/App/Curves/Curves.csproj
Include the library in the library project.
Update to NCalc2 that is supported under .NET Standard.
> VIX-2903 Fix the missing NCalc library.

- Common/Controls/TimeLineControl/Grid.cs
- Modules/Editor/TimedSequenceEditor/TimedSequenceEditorForm.Designer.cs
- Modules/Editor/TimedSequenceEditor/TimedSequenceEditorForm.cs
- Modules/Editor/TimedSequenceEditor/TimedSequenceEditorForm_Menu.cs
Add menu item under the View to select to show the tool tip.
Add shortcut Ctrl+I that will toggle the tool tip and remove it from the drag box filter selection which is unlikely to be used.
Add logic to save the setting to the normal editor settings.
Add logic to the grid drawing routine to draw based on the setting.
> VIX-2904 Add option to toggle the effect info tool tip.

- Modules/App/CustomPropEditor/Model/Prop.cs
- Modules/App/CustomPropEditor/ViewModels/ElementModelViewModel.cs
- Modules/App/CustomPropEditor/ViewModels/PhysicalMetadataViewModel.cs
- Modules/App/CustomPropEditor/ViewModels/PropEditorViewModel.cs
- Modules/App/CustomPropEditor/ViewModels/VendorMetadataViewModel.cs
The upgrade to newer versions of Catel exposed a few new properties in view models that the Property Grid was dynamically picking up. Added logic to override and add the browsable attribute to them to suppress them.
Added some tool tip descriptions to a few other fields to help the user with their meaning.
Populate the created by field with the system user name so it has some default.
> VIX-2920 Fix up Prop Editor fields.

- Modules/Effect/Text/Text.cs
The level value was not being initialized before the initial render operation happened on the first frame. This was causing the first frame to have transparent text on the the initial render. It is a class level variable, so the next time it rendered it would have the last value which if positive would produce a non transparent frame. I moved the initialization of that variable to ensure it happens correctly.
> VIX-2934 Fix an issue where the first frame text would be black.

- Application/VixenApplication/ConfigPreviews.Designer.cs
- Application/VixenApplication/ConfigPreviews.cs
- Modules/Preview/VixenPreview/Shapes/DisplayItem.cs
- Modules/Preview/VixenPreview/Shapes/PreviewArch.cs
- Modules/Preview/VixenPreview/Shapes/PreviewBaseShape.cs
- Modules/Preview/VixenPreview/Shapes/PreviewCane.cs
- Modules/Preview/VixenPreview/Shapes/PreviewCustom.cs
- Modules/Preview/VixenPreview/Shapes/PreviewCustomProp.cs
- Modules/Preview/VixenPreview/Shapes/PreviewEllipse.cs
- Modules/Preview/VixenPreview/Shapes/PreviewIcicle.cs
- Modules/Preview/VixenPreview/Shapes/PreviewLine.cs
- Modules/Preview/VixenPreview/Shapes/PreviewMegaTree.cs
- Modules/Preview/VixenPreview/Shapes/PreviewMultiString.cs
- Modules/Preview/VixenPreview/Shapes/PreviewNet.cs
- Modules/Preview/VixenPreview/Shapes/PreviewPixelGrid.cs
- Modules/Preview/VixenPreview/Shapes/PreviewPoint.cs
- Modules/Preview/VixenPreview/Shapes/PreviewPolyLine.cs
- Modules/Preview/VixenPreview/Shapes/PreviewRectangle.cs
- Modules/Preview/VixenPreview/Shapes/PreviewSingle.cs
- Modules/Preview/VixenPreview/Shapes/PreviewStar.cs
- Modules/Preview/VixenPreview/Shapes/PreviewStarBurst.cs
- Modules/Preview/VixenPreview/Shapes/PreviewTriangle.cs
- Modules/Preview/VixenPreview/VixenPreviewData.cs
Add UI elements and logic in the ConfigPreviews to duplicate selected previews.
Core changes to the make sure the clone methods on all the shapes work correctly and make a unlinked duplicate of the shapes. This looks more invasive than it actually was. All the shapes were touched as many of them did not have a proper clone override. Some of them did, but it was not making a proper deep clone of all items.
> VIX-2933 Add ability to duplicate a preview.

- Modules/Editor/PolygonEditor/Adorners/ResizeAdorner.cs
- Modules/Editor/PolygonEditor/Views/PolygonEditorView.xaml.cs
Removed some logic that was trying to assist when resizing to the edges.  It was only on the the middle top adorner so it was unbalanced anyway.
The other issue was with a Math.Round that was not doing what I thought it was doing.  Replaced it with Math.Ceiling.
> VIX-2953 Polygon editor locked up while resizing a polygon

- Application/VixenApplication/VixenApplication.cs
- Application/VixenApplication/VixenApplication.csproj
- Modules/App/SuperScheduler/SuperSchedulerDescriptor.cs
- Modules/App/SuperScheduler/SuperSchedulerModule.cs
- Modules/Sequence/Timed/Timed.csproj
- Modules/Sequence/Timed/TimedSequenceMigrator.cs
- Vixen.System/Sys/VixenSystem.cs
Suppress the migration message when not on the UI thread.
Fix a threading issue with starting the scheduler from the module startup that occurs in a non UI thread. This is workaround until a better solution can be found.
> VIX-2961 Fix Scheduler hang with sequences that need to be migrated.

- Application/VixenApplication/VixenApplication.cs
- Application/VixenApplication/VixenApplication.csproj
- Modules/App/Scheduler/SchedulerModule.cs
- Modules/App/SuperScheduler/ScheduleExecutor.cs
- Modules/App/SuperScheduler/SuperSchedulerModule.cs
- Vixen.System/Sys/VixenSystem.cs
Store off the UI context for later use. Use that to run the forms in the modules when they start forms so they are in the proper UI context.
Revert the temporary workaround.
> VIX-2961 Resolve the synchronization issues in the Scheduler.

- Modules/Editor/PolygonEditor/ViewModels/PolygonEditorViewModel.cs
- Modules/Editor/PolygonEditor/Views/PolygonEditorView.xaml.cs
Original fix to (VIX-2953) was to take the ceiling of the scaled width and height. This had the potential to add some fractional slop to the drawing canvas. To fix this, I moved the logic to calculate the canvas size up so that the final scale factor can be based on the canvas size and the original display element size.
Once the scale factor was improved I noticed on my mega-tree that the scaling produced some floating point error which prevented the user from resizing the polygon. To account for the floating point error I added some rounding in the IsTransformValid method.
Finally I noticed there was an inconsistency on how single width display elements like arches were being scaled. This was updated to be consistent between the X and Y.
> VIX-2953 - Fix scaling math

- Modules/Effect/Wave/Wave/Wave.cs
The fix for VIX-2941 was incomplete.  I think I got too much in hurry / over confident and did not test sufficiently.
The property on the effect needs be the most derived type for the reflection to work properly.
> VIX-2969 Fix WaveType on Wave Effect

- Modules/Effect/LipSync/LipSync.cs
When there are no marks to work from and mark collection is selected as the type, the REST phoneme will be used. The rendering routine in the effect was not drawing anything. Added the logic to draw the default path.
> VIX-2986 Fix the editor rendering of the Lipsync.

- Application/VixenApplication/VixenApplication.cs
- Vixen.System/Sys/VixenSystem.cs
The saves when a user opens the Display setup or the Preview setup occur on a background thread to free up the UI. But the user is not prevented from opening the other setup while that is occurring. If they do that and close it before the other save completes, then conflicts can occur. Add logic to disable the buttons while the save is occurring. Add indicator in the progress bar on the admin that saving is in progress so the user is aware of what is going on.
Add wait cursors while saves are occurring.
Add the same blocking logic and progress indicator for the cancel path when the system is being reloaded.
Change the backup logic from a File move to a File copy to improve the performance. For some reason the move randomly is much slower. Copy seems to perform much faster and more …
> VIX-2987 Fix conflicts when rapid saves occur.

- Modules/Output/DummyLighting/DummyLighting.cs
Now that the profile modules are loading in a background thread, the DummyLighting was creating its form in the constructor instead of in the Start method and the form was not on the same thread as the message loop. Refactor the logic to create the form on the Start method correctly to solve the cross threading issue.
> VIX-2999 Fix a threading issue in the DummyLighting Controller

- Modules/Preview/VixenPreview/Shapes/PreviewCustomProp.cs
The move to logic was not scaling the movement offset back to the original zoom level that the prop coordinates are in and thus was multiplying the movement. This created erratic behavior the further from the original location the mouse was moving toward. Apply the reverse zoom logic to the move offset to get it into the same coordinate plane.
> VIX-3011 Correct the MoveTo logic to account for Zoom level.

- Modules/Preview/VixenPreview/VixenPreviewControl.cs
- Modules/Preview/VixenPreview/VixenPreviewSetup3.cs
There are some cases where the default blank background will not be the same size as the view port. Change the logic to calculate the view port size and use that to determine if props are outside the viewable range.
> VIX-2878 Amend the fix from this original bug around rogue props in the preview.

- Common/Controls/TimeLineControl/Grid.cs
- Modules/Editor/TimedSequenceEditor/TimedSequenceEditorForm_Hotkeys.cs
Add logic to the key stroke handler to prevent an alignment event if effects are being resized or moving. Added the logic to expose if the move/resize is occurring.
> VIX-3017 Fix crash during alignment when effect is moving or resizing.

- Modules/Preview/VixenPreview/Shapes/PreviewCustomProp.cs
- Modules/Preview/VixenPreview/VixenPreviewSetup3.cs
- Modules/Preview/VixenPreview/VixenPreviewSetupPropertiesDocument.cs
Add the Top Left and Bottom Right fields.
Add logic to update them on any movement so you have live updates when moving a single prop.
Fix a bug that would reload the property viewer on mouse up even if the shape was already being edited. This was introducing an annoying flicker.
> VIX-3016 Add size fields to the Custom Prop similar to other shapes.

- Common/Controls/TimeLineControl/TimelineControl.cs
A seemingly do nothing line of code was removed in a previous change, however it was compensating for events being disabled after rows were resized. There is likely a better way to solve this in the future, but for now restored the line of code with some comments indicating its purpose.
> VIX-3018 Correct row zoom bug.

- Modules/Preview/VixenPreview/VixenPreviewSetup3.cs
The logic does not account for single Preview Pixels that their coordinates are exposed in a non standard way. Amend to ensure the coordinates are in the same place.
> VIX-3019 Fix the logic looking for zero size shapes.

- Modules/Effect/Tree/Tree.cs
Added compensation logic to the Speed logic to offset it from the expected 50ms when the real rate is different. This uses the real frame rate divided by the standard 50ms to create the offset multiplier.
> VIX-3026 Fix issue with timing changing when the frame rate changes.

- Modules/Preview/VixenPreview/VixenPreviewSetup3.Designer.cs
- Modules/Preview/VixenPreview/VixenPreviewSetup3.cs
- Modules/Preview/VixenPreview/VixenPreviewSetupPropertiesDocument.cs
If a display item is selected, and then an element is selected or blank space in the preview is clicked; when the display item is reselected the properties do not appear.
I found that this was being caused because in the `VixenPreviewSetupPropertiesDocument` the _setupControl wasn't being cleared when the Controls were being cleared which resulted in `VixenPreviewSetup3` not re-rendering the properties.
New functionality with this edit:
> Preview Changes

- Modules/App/ExportWizard/BulkExportOutputFormatStage.cs
- Modules/App/ExportWizard/BulkExportSummaryStage.cs
The 1.x FPP export flow was not properly updating the move next button. Changed the criteria to validate the correct folder.
The logic was also trying to export the new universe file to the 2.x folder which may not be specified. Fixed that logic.
> VIX-2988 Fix a couple issues in the legacy FPP export.

- Modules/App/CustomPropEditor/Import/XLights/XModelInventoryMapper.cs
- Modules/App/CustomPropEditor/Model/ExternalVendorInventory/Model.cs
The model id is not used in our flow so it is not critical that it be populated, so will add logic to handle if it is missing and let it default to zero.
> VIX-3071 Logic to handle missing ids.

- Common/FMOD/fmod_wrapper.cs
This is not the most robust solution, but this whole sound driver setup needs to be replaced anyhow. This will provide a band aid for my unique situation until that comes along.
> VIX-3072 Add logic to skip known specialty audio devices.

- Common/Controls/NumericTextBox.cs
The field is a double value, so a period is a valid character. Added logic to handle just a period intead of letting the parser fail trying to parse it.
> VIX-3078 Add logic to prevent crash on period entry.

- Modules/Preview/VixenPreview/Shapes/PreviewShapeBaseSetupControl.cs
The change event can fire from a background thread and when it tries to invoke on the UI components, it needs to be on the UIThread. Add logic to detect and switch the thread context in the change event handler.
> VIX-3107 Fix cross threading issue causing preview crash.

- Modules/Effect/Bars/BarsData.cs
VIX-3109
Fixing the default of the rotation to zero.  This should make the effect behave by default like it did before rotation and zig zag were added.
> VIX-3109 Update BarsData.cs

- Common/WPFCommon/Converters/PercentageConverter.cs
The Convert.ToDouble method is culture specific and users in cultures that use a comma for a decimal were seeing issues parsing the values in the PercentageConverter. Add option to parse with InvariantCulture to handle US decimal value coded in the percentage.
> VIX-3035 Fix application crash in sequence import.

- Modules/PostFilter/DimmingCurve/DimmingCurveModule.cs
The logic for the command intent was dividing by 100 when it did not require and was creating incorrect values.
> VIX-3122 Fix a math bug in the dimming curve.

- Modules/App/Curves/FunctionGenerator.resx
- Modules/PostFilter/DimmingCurve/DimmingCurveModule.cs
Found other issues with the math logic converting back and forth when using more examples.
Added documentation as to how it works so it is easier to understand later.
Updated the text example of a Gamma curve formula to be more correct. A 2.8 Gamma is very aggressive. The formula also generated a small zero value that could keep items from being truly off at zero so I corrected the example and worded it in a way that hopefully makes it easier for a user to understand.
> VIX-3122 Fix the math logic for real this time.

- Application/VixenApplication/SelectProfile.cs
Recent changes in VIX-988 introduced a bug that tries to clear the profile list box when a datasource is set. Changed the logic back to load the list items in a foreach after sorting to avoid using the datasource. This issue appears when the profile list is loaded a second time, most notably creating a new profile when others already exist.
> VIX-3142 Fix a bug in the profile selection screen that crashes Vixen.

- Vixen.System/Module/ModuleDataModelBase.cs
Remove the DataMember attribute from the field data for Module Instance and type ids as they are stored by the serializer as an attribute which duplicates them.
> VIX-3148 Work to reduce the size of the ModuleStore

- Common/Controls/TimeLineControl/Grid.cs
Remove unnecessary info logging in the Grid class.
Remove dead code and commented code that is not needed.
> VIX-3164  Code cleanup

- Application/VixenApplication/Setup/SetupControllersSimple.cs
- Application/VixenApplication/Setup/SetupElementsTree.cs
Added logic to both the element and controller logic that selects the patch points for the selected items. If none are found a informational dialog is presented to notify the user.
> VIX-3119 Add no patch points found dialog.

- Modules/Output/E1.31/E131OutputPlugin.cs
If the controller does not have an IP address set, use the loopback as a default for the export configuration to prevent crashes.
> VIX-3254 Fix export crash when controller is missing IP address.

- Modules/App/CustomPropEditor/Import/XLights/XModelInventoryMapper.cs
- Modules/App/CustomPropEditor/ViewModels/PropEditorViewModel.cs
- Modules/App/CustomPropEditor/ViewModels/VendorInventoryWindowViewModel.cs
- Modules/App/TimingTrackBrowser/ViewModels/VendorInventoryWindowViewModel.cs
Fix issue with the vendor url not opening on the singing faces project. Update to the new api to replace the deprecated form of opening a browser.
Fix issues with parsing the weblinks vendors provide in their custom props. Add logic to try and add the http:// when the vendor does not have that as part of the url.
> VIX-3255 Fix several issues with vendor url formatting.

- Installer/Installer.nsi
Add logic to include the PDB files when running the installer setup for a dev build.
> VIX-3256 Include PDB files to dev installer.

- Common/WPFCommon/Styles/DefaultHiddenStyleResourceDictionary.cs
- Common/WPFCommon/Theme/DefaultHiddenStyle.xaml
- Common/WPFCommon/Theme/Theme.xaml
- Common/WPFCommon/WPFCommon.csproj
The default style for the context menu was not being applied on controls since it is hidden. Add a bit of logic to inject our style through code.
https://stackoverflow.com/questions/30940939/wpf-default-textbox-contextmenu-styling
> VIX-3215 Fix white context menu issue in WPF controls.

- Modules/Effect/Effect/FixtureEffectBase.cs
- Modules/Effect/Effect/FixtureIndexEffectBase.cs
- Modules/Effect/Gobo/GoboModule.cs
VIX-3260 Intelligent Fixture Effects cause exception when pasting to another display element
> VIX-3260 Intelligent Fixture Effects cause exception when pasting to another display element

- Common/AudioPlayer/CoreAudioPlayer.cs
- Common/AudioPlayer/SampleProvider/SoundTouchSource.cs
* Default the Sound Touch source tempo to a default of 1 so audio plays normal by default. This was causing the scheduler audio to be processed when it shouldn't. The sound touch processor has a read to end bug that was causing the playback to stick and the end which hangs the scheduler.
* Don't dispose the sound out in the playback ends event since it cannot be cleaned up from the play thread. This was causing crashes in the scheduler when the schedule is stopped.
> VIX-3268 Fix scheduler crash with audio library.

- Modules/Preview/VixenPreview/Shapes/MovingHeadIntentHandler.cs
VIX-3262 Intelligent Fixture Preview is not properly clearing the legend
> VIX-3262 Intelligent Fixture Preview is not properly clearing the legend

- Modules/Editor/LayerEditor/LayerEditorView.cs
- Modules/Editor/LayerEditor/Themes/Generic.xaml
For some reason the dependency property is not attaching correctly and then the drag drop logic does not work. No obvious code change in this area in a long time, so I can't determine when or why it stopped working. Manually added it in code as a work around.
> VIX-3284 Fix drag drop in the layer editor.

- Modules/Editor/FixturePropertyEditor/ViewModels/FunctionItemViewModel.cs
VIX-3287 Intelligent Fixture Wizard - Function Tag drop down is entirely empty for the None Function
> VIX-3287 Intelligent Fixture Wizard - Function Tag drop down is entirely empty for the None Function

- Modules/Preview/VixenPreview/Shapes/MovingHeadIntentHandler.cs
VIX-3288 Intelligent Fixture Preview - Add the ability to strobe when color wheel color is generated directly from Fixture Effect
> VIX-3288 Intelligent Fixture Preview - Add the ability to strobe when color wheel color is generated directly from Fixture Effect

- Modules/Effect/Effect/FixtureEffectBase.cs
VIX-3299 Fixture Effect - 'None' is showing up a function the user can pick and add to the effect
> VIX-3299 Fixture Effect - 'None' is showing up a function the user can pick and add to the effect

- Common/AudioPlayer/CoreAudioPlayer.cs
The new audio logic was not accounting for play pause resume correctly which could hang the audio player. Adjust the logic to resume when paused instead of trying to play.
> VIX-3304 Fix hang when using play / pause buttons.

- Modules/App/TimedSequenceMapper/SequenceElementMapper/Models/ElementMap.cs
The linq query was being re-evaluated once it was added to the source ids and the list was being modified. This was not allowing the map add to occur. Force the linq query to a one time evaluation by adding a toList.
> VIX-3309 Fix issue where adding to maps would not work.

- Common/Controls/ElementTree.cs
- Modules/Preview/VixenPreview/VixenPreviewControl.cs
- Modules/Preview/VixenPreview/VixenPreviewSetupElementsDocument.cs
Add logic to validate if the element still exists or not before unlinking to the delete routine. T
Add logic to trigger the remove action event args when nodes are deleted so they will properly update.
Fix a loop hole in the Reload method that could allow shapes to remained linked if just the nodeId is set. This is probably a corner case, but could happen.
Add logic to ensure when custom Props are added they are properly added to the NodeToPixel mapping and the highlight logic is called.
All of these changes were part of a final commit in the branch that I somehow lost in the original fix for VIX-3289 when I pushed the changes.
> VIX-3316 Fix issues related to VIX-3289 due to missing code commit.

- Modules/Effect/SetLevel/SetLevel.cs
VIX-3331 - SetLevel when applied to a group is not correctly creating an intent for the specific leaf node
> VIX-3331 - SetLevel when applied to a group is not correctly creating an intent for the specific leaf node

- Modules/Effect/Candle/CandleModule.cs
All candle effects rendering at the same time would have the same pattern since the random seed was not very random. Switched it to use the global random in the base calls for effects that will ensure it is much more random.
> VIX-3363 Improve the randomness across candle effects.

- src/Vixen.Application/CheckForUpdates.cs
- src/Vixen.Common/Help/Help.cs
- src/Vixen.Common/WPFCommon/Controls/NavigatableHyperLink.cs
- src/Vixen.Modules/App/Curves/FunctionGenerator.cs
- src/Vixen.Modules/App/Curves/ZedGraph/ZedGraphControl.Events.cs
- src/Vixen.Modules/App/CustomPropEditor/ViewModels/PropEditorViewModel.cs
- src/Vixen.Modules/App/Modeling/ElementModeling.cs
- src/Vixen.Modules/App/TimedSequenceMapper/SequenceElementMapper/ViewModels/ElementMapperViewModel.cs
- src/Vixen.Modules/App/WebServer/Settings.cs
- src/Vixen.Modules/Editor/FixturePropertyEditor/Views/FixturePropertyEditorWindowView.xaml.cs
- src/Vixen.Modules/Editor/FixturePropertyEditor/Views/FunctionTypeWindowView.xaml.cs
- src/Vixen.Modules/Editor/FixtureWizard/Wizard/Models/IntelligentFixtureWizard.cs
- src/Vixen.Modules/Preview/VixenPreview/VixenPreviewSetup3.cs
* Add UseShellExecute = true in areas that use a url or file path so the OS can determine the proper application. This was defaulted to true in .NET Framework and now defaults to false in .NET Core.
> VIX-3382 Fix Process.Start for areas that use a url

- src/Vixen.Modules/App/CustomPropEditor/ViewModels/PropEditorViewModel.cs
- src/Vixen.Modules/App/TimedSequenceMapper/SequenceElementMapper/ViewModels/ElementMapperViewModel.cs
- src/Vixen.Modules/Editor/TimedSequenceEditor/Forms/Form_Marks.cs
- src/Vixen.Modules/Preview/VixenPreview/VixenPreviewControl.cs
* Introduce the use of DetermineOpenFileContext and DetermineSaveFileContext to the open and save file usages. This is mainly reorganizing how the parameters are passed to setup the file dialog.
* Some minor changes to the initial directory settings were made to conform with the new pattern. This should mostly behave the same or default to the root of the profile.
* Remove deprecated CloseViewModelOnUnloaded call. This was just setting it to the default behavior, so should be no harm in removing.
> VIX-3417 Catel Deprecations.

- src/Vixen.Common/Controls/TimeLineControl/Waveform.cs
- src/Vixen.Common/NShape/Project.cs
- src/Vixen.Common/NShape/XmlStore.cs
- src/Vixen.Common/NShapeWinFormsUI/LibraryManagementDialog.cs
- src/Vixen.Common/WpfPropertyGrid/Internal/MergedPropertyDescriptor.cs
- src/Vixen.Core/Execution/DataSource/EffectNodeDataPump.cs
- src/Vixen.Core/Execution/DataSource/SequenceDataPump.cs
- src/Vixen.Modules/App/CustomPropEditor/Model/InternalVendorInventory/Product.cs
- src/Vixen.Modules/App/Marks/Annotations.cs
- src/Vixen.Modules/App/Marks/BindableBase.cs
- src/Vixen.Modules/App/Marks/MarkDecorator.cs
- src/Vixen.Modules/App/WebServer/Module.cs
- src/Vixen.Modules/App/WebServer/WebHost.cs
- src/Vixen.Modules/Controller/E131/AboutBox.cs
- src/Vixen.Modules/Editor/EffectEditor/Editors/PolygonContainerTypeEditor.cs
- src/Vixen.Modules/Editor/EffectEditor/Internal/MergedPropertyDescriptor.cs
- src/Vixen.Modules/Editor/FixturePropertyEditor/Views/ColorWheelView.xaml.cs
- src/Vixen.Modules/Editor/FixturePropertyEditor/Views/FixturePropertyEditorView.xaml.cs
- src/Vixen.Modules/Editor/FixturePropertyEditor/Views/FunctionTypeView.xaml.cs
- src/Vixen.Modules/Editor/FixturePropertyEditor/Views/IndexedView.xaml.cs
- src/Vixen.Modules/Editor/TimedSequenceEditor/TimedSequenceEditorForm_Toolstrip.cs
- src/Vixen.Modules/Effect/Effect/PixelEffectBase.cs
- src/Vixen.Modules/Effect/Morph/Directory.Build.props
- src/Vixen.Modules/Effect/Morph/Morph/Morph.cs
- src/Vixen.Modules/Effect/Video/Video.cs
- src/Vixen.Modules/Media/Audio/SampleProviders/MonoSampleProvider.cs
- src/Vixen.Modules/OutputFilter/DimmingCurve/DimmingCurveModule.cs
- src/Vixen.Modules/Preview/VixenPreview/Shapes/PreviewLightBaseShape.cs
- src/Vixen.Modules/Preview/VixenPreview/Shapes/PreviewMovingHeadPartial.cs
* Remove many unused variables.
* Suppress warnings for BinaryFormatter since the usage here is fine.
* Fix nullable warnings for several classes either by adding nullable attribute to file, or fixing the build props.
> VIX-3421 Fix variety of basic warnings.

- src/Vixen.Modules/Editor/FixtureGraphics/OpenGL/Shaders/VolumeShader.cs
VIX-3426 Fixing warnings with respect to obsolete OpenTK method arguments
> VIX-3426 Fixing warnings with respect to obsolete OpenTK method arguments

- src/Vixen.Core/Sys/ElementNode.cs
* The null check added for the nullable logic was placed int he wrong area. Refactored to move it to the correct place to restore previous functionality.
> VIX-3428 Fix null check code

- src/Vixen.Modules/App/CustomPropEditor/ViewModels/PropEditorViewModel.cs
* Vendors may not use a direct link to the file so the logic trying to look for another file with a different extension does not work correctly. With the pervasive use of drop box style file shares, the assumption made when this code was written is not valid. Removed the logic since it is not being used anyway.
> VIX-3431 Remove logic looking for Vixen Prop files

- .github/workflows/release_build.yml
* 32 bit builds are deprecated so removing the steps from the action pipeline that build and publish a 32 bit build.
> VIX-3443 Remove 32 bit builds from the CICD pipeline

- src/Vixen.Common/Controls/TimeLineControl/Ruler.cs
* Add logic in the Ruler class to clamp the playback start and end to the proper bounds.
> VIX-3453 Fix time selection bug

- src/Vixen.Common/Controls/TimeLineControl/Grid.cs
- src/Vixen.Common/Controls/TimeLineControl/Grid_Mouse.cs
- src/Vixen.Common/Controls/TimeLineControl/LabeledMarks/TimeLineGlobalEventManager.cs
- src/Vixen.Common/Controls/TimeLineControl/MarksBar.cs
- src/Vixen.Common/Controls/TimeLineControl/Ruler.cs
- src/Vixen.Common/Controls/TimeLineControl/TimeLineGlobalStateManager.cs
- src/Vixen.Common/Controls/TimeLineControl/TimelineControl.cs
- src/Vixen.Common/Controls/TimeLineControl/Waveform.cs
- src/Vixen.Modules/Analysis/BeatsAndBars/PreviewWaveform.cs
- src/Vixen.Modules/Editor/TimedSequenceEditor/Forms/Form_Grid.Designer.cs
- src/Vixen.Modules/Editor/TimedSequenceEditor/Forms/Form_Grid.cs
- src/Vixen.Modules/Editor/TimedSequenceEditor/TimedSequenceEditorForm.cs
* Modify the global event handlers to accept an id so they can maintain multiple versions for each editor that requests to use it.
* Modify the sequence editor to have a unique id that can be used to request a per editor event manager.
* Modify the child components that require use of the event managers to accept the parent id so they can request the proper event manager.
> VIX-3454 Fix events occuring across mutiple editors

- src/Vixen.Core/Sys/Managers/ContextManager.cs
* Looks like the the editor was closing and the context may have already been released.
> VIX-3437 Add null checking on context release.

- src/Vixen.Modules/Effect/Shapes/Shapes.cs
- src/Vixen.Modules/EffectEditor/EffectDescriptorAttributes/EffectDescriptionDescriptors.resx
- src/Vixen.Modules/EffectEditor/EffectDescriptorAttributes/EffectDisplayNameDescriptors.resx
* Fix the Marks Collection tool tip to use the proper name and description from the resource file.
* Fix the Movement tool tip.
* Add a shape specific fade type tool tip to the resource file.
* Correct the Size setting description.
> VIX-3405 Fix improper tool tips in the Shapes effect

- src/Vixen.Common/Controls/ControllerTree.cs
- src/Vixen.Core/Module/Controller/ControllerModuleInstanceBase.cs
- src/Vixen.Core/Module/SmartController/SmartControllerModuleInstanceBase.cs
- src/Vixen.Core/Sys/Output/IUpdatableOutputCount.cs
- src/Vixen.Core/Sys/Output/OutputController.cs
- src/Vixen.Modules/Controller/OpenDMX/OpenDMXInstance.cs
* Add logic to allow controller instances to set an output limit they support.
* Add logic to pass the controller limit to the input dialog to constrain the input limit.
* Set default channel count to 1 instead of 0.
> VIX-3448 Fix controller limit

- src/Vixen.Modules/Editor/TimedSequenceEditor/Forms/Form_AddMultipleEffects.Designer.cs
- src/Vixen.Modules/Editor/TimedSequenceEditor/Forms/Form_AddMultipleEffects.cs
- src/Vixen.Modules/Editor/TimedSequenceEditor/Forms/Form_AddMultipleEffects.resx
- src/Vixen.Modules/Editor/TimedSequenceEditor/TimedSequenceEditorForm.cs
* Add new checkbox to select the option for mark start and end time for alignment.
* Fix longstanding issues with checkbnoxes being enabled and disabled based on the choices.
* Fix skip logic to allow for the proper count when an odd number of marks are available.
> VIX-3339 Add ability to align effects to mark start and end time

- src/Vixen.Common/AudioPlayer/CoreAudioPlayer.cs
VIX-3461 Vixen crashes after a sequence is played
Adding dispose logic after sequence is done playing.
> VIX-3461 Vixen crashes after a sequence is played

- src/Vixen.Common/AudioPlayer/AudioPlayer.csproj
- src/Vixen.Common/AudioPlayer/CoreAudioPlayer.cs
VIX-3465 Fixing audio looping logic to avoid already initialized exception
> VIX-3465 Fixing audio looping logic to avoid already initialized exception

- src/Vixen.Common/Controls/TimeLineControl/LabeledMarks/MarksSelectionManager.cs
- src/Vixen.Common/Controls/TimeLineControl/MarksBar.cs
- src/Vixen.Common/Controls/TimeLineControl/Ruler.cs
- src/Vixen.Modules/Editor/TimedSequenceEditor/TimedSequenceEditorForm.cs
* Apply the same changes to the MarkSelectionManager as were applied to TimelineGlobalEventManager in the previous fix.
> VIX-3454 Fix additional issue with Mark selection events overlapping

- src/Vixen.Modules/Preview/VixenPreview/Shapes/PreviewBaseShape.cs
- src/Vixen.Modules/Preview/VixenPreview/VixenPreviewControl.cs
- src/Vixen.Modules/Preview/VixenPreview/VixenPreviewSetup3.cs
* Add property to the settings grid to set if the prop uses common location for all nodes.
* Add logic to the location assignment to check the property and update the locations with real or center location.
* Fix a bug in the location assignment that was not using the location offset.
> VIX-3472 Add logic for making a prop have a central location

- src/Vixen.Core/Delegates/Delegates.cs
- src/Vixen.Modules/App/ExportWizard/BulkExportSummaryStage.cs
* Catch exceptions during the sequence load and prompt the user with the sequence that failed and ask if they would like to continue.
> VIX-3486 Add logic to catch sequence load errors in the export

- src/Vixen.Application/Setup/ElementTemplates/PixelGrid.cs
* Top Left and Bottom Right need additional logic to correctly order the patching when they are in a vertical orientation.
> VIX-3482 Fix patching order logic in the Matrix wizard

- src/Vixen.Core/Export/Export.cs
- src/Vixen.Core/Export/FPP/Universe.cs
- src/Vixen.Core/Module/Controller/ControllerNetworkConfiguration.cs
- src/Vixen.Modules/Controller/E131/E131OutputPlugin.cs
Condense Universe lines for FPP export so that there is one line per controller when universes are same size.  Also added fields for monitor and dedup to set them accordingly from the vixen controller settings.
> VIX-3499  Condense Universe lines for FPP export so that there is one line per controller when universes are same size.

- src/Vixen.Modules/Preview/VixenPreview/Shapes/PreviewMovingHead.cs
- src/Vixen.Modules/Preview/VixenPreview/VixenPreviewControl.cs
VIX-3511 - Can't select intelligent fixtures from bottom right towards top left. Updated how preview rubber banding works, see ticket notes for further details.
> VIX-3511 - Can't select intelligent fixtures from bottom right towards top left

- src/Vixen.Modules/Editor/TimedSequenceEditor/TimedSequenceEditorForm_Toolstrip.cs
Timing speed label occasionally showed decimal places for certain speeds, this fixes that.
> VIX-3471 Changed formatting code for timing speed label

- src/Vixen.Modules/Controller/E131/SetupForm.cs
This prevents a user from clicking the delete unicast destination button without a destination selected.
> VIX-3529 Add delete unicast destination logic

- src/Vixen.Core/Commands/Named8BitCommand.cs
- src/Vixen.Modules/Editor/FixtureGraphics/IMovingHead.cs
- src/Vixen.Modules/Editor/FixtureGraphics/MovingHeadSettings.cs
- src/Vixen.Modules/Effect/Effect/FixtureEffectBase.cs
- src/Vixen.Modules/Preview/VixenPreview/OpenGL/OpenGLPreviewForm.cs
- src/Vixen.Modules/Preview/VixenPreview/Shapes/IOpenGLMovingHeadShape.cs
- src/Vixen.Modules/Preview/VixenPreview/Shapes/MovingHeadIntentHandler.cs
- src/Vixen.Modules/Preview/VixenPreview/Shapes/MovingHeadTimer.cs
- src/Vixen.Modules/Preview/VixenPreview/Shapes/PreviewMovingHead.cs
- src/Vixen.Modules/Preview/VixenPreview/Shapes/PreviewMovingHeadPartial.cs
- src/Vixen.Modules/Preview/VixenPreview/VixenPreviewControl.cs
VIX-3513  Intelligent fixture wizard doesn't copy pan/tilt start/end properties
This branch is based off of VIX-3519.  It is probably going to need to be rebased after VIX-3521 is merged.
> VIX-3513  Intelligent fixture wizard doesn't copy pan/tilt start/end properties

- .github/workflows/compile_test.yml
- .github/workflows/release_build.yml
* Several modules are throwing node.js 16 deprecations. Update to the current versions to avoid future failed builds
> VIX-3557 Update git action module

- src/Vixen.Modules/App/CustomPropEditor/CustomPropEditor.csproj
- src/Vixen.Modules/App/CustomPropEditor/Services/PropModelPersistenceService.cs
* The new version has a 16mb document size limit that the old version did not and this causes a problem with large props. Will need to look for an alternate solution.
This reverts commit 2a946ab87bf66e1660ea3b590dea3549e7d55964.
> VIX-3561 Revert "VIX-3530 Upgrade LiteDB library"

- src/Vixen.Common/Controls/ElementTree.cs
* Added logic to refresh the tree if an element was added to an existing group. This is a workaround for the logic that generates node paths only returning one path to the group.
* An eventual fix should be made to fix the flaw in the node path logic flows that do not account for multiple paths to the same element. VIX-3574 was created to fix the bigger issue with the paths.
> VIX-3573 Fix newly added element not showing in the tree when part of multiple groups

- src/Vixen.Modules/App/CustomPropEditor/CustomPropEditorData.cs
- src/Vixen.Modules/App/CustomPropEditor/Model/Configuration.cs
- src/Vixen.Modules/App/CustomPropEditor/Model/ElementModel.cs
- src/Vixen.Modules/App/CustomPropEditor/Services/PropModelServices.cs
- src/Vixen.Modules/App/CustomPropEditor/ViewModels/ConfigurationWindowViewModel.cs
- src/Vixen.Modules/App/CustomPropEditor/ViewModels/PropEditorViewModel.cs
- src/Vixen.Modules/App/CustomPropEditor/Views/ConfigurationWindow.xaml
* Add option to the Options -> Preferences to set the default light size for newly created lights.
* Persist the setting to the configuration data section so it appears each new session. This is per profile.
* Add logic to use the configuration setting when adding a light.
> VIX-3575 Allow default light size preference

- src/Vixen.Modules/App/CustomPropEditor/CustomPropEditor.csproj
- src/Vixen.Modules/App/CustomPropEditor/ViewModels/PropEditorViewModel.cs
- src/Vixen.Modules/App/CustomPropEditor/Views/CustomPropEditorWindow.xaml
- src/Vixen.Modules/App/Modeling/ElementModeling.cs
* Update the modeling project to support sending data to export in a form other than actual elements. These do not exist in the prop editor.
* Add menu item under tools to invooke the export function.
* Add constants for the over size dimensions.
> VIX-3577 Add export model function to the custom prop editor

- src/Vixen.Application/NLog.config
VIX-3584 Configure NLog not to keep files open so that profile can be zipped up
> VIX-3584 Configure NLog not to keep files open so that profile can be zipped up

- src/Vixen.Application/Setup/SetupPatchingSimple.cs
- src/Vixen.Common/Controls/ControllerTree.cs
* The selection was not being cleared after the outputs where removed and downstream code was crashing with index out of bounds.
* Fix improper check on the index bounds that was not accounting for 0 based indexing. This was causing the crash becasue of bad input.
> VIX-3588 Fix crash when removing outputs

- src/Vixen.Modules/Controller/DDP/DDPData.cs
- src/Vixen.Modules/Controller/DDP/DDPSetup.cs
* Initial IP Address string is formated with commas instead of periods between the numbers and the parse fails. Set the default to use the IPAddress.Loopback field string value in order to get a correct value.
* Fix the logic in the constructor to use TryParse on the string value saved in the data object to ensure it is protected in case of a improper value. If it is not parsable, default to Loopback.
* Change the set/get for IPAddress to use Loopback if they have a null value. With the other changes, this really should not occur, but ensures at least a valid value in all cases.
> VIX-3598 Fix crash in setup of new DDP Controller

- src/Vixen.Modules/Preview/VixenPreview/Shapes/PreviewCustom.cs
* The clone method in PreviewCustom was incorrectly adding strings to the underlying collection that has overriden function that does not work when you directly add to the cloolection. Build the new string collection and then update the property with that collection to elicit functional behavior. This PreviewCustom is deprected so this is the minumal fix to get it working for legacy users.
> VIX-3593 Fix issue with clone preventing proper duplication of preview

- src/Vixen.Modules/Sequence/Timed/TimedSequenceMigrator.cs
* Add logic in the sequence migrator that will find deprecated Nutcracker effects and remove them.
* Alert the user that the effects were removed and provide instruction on how to migrate them to prevent loss.
> VIX-3606 Add logic to detect and remove deprecated Nutcracker effects

- src/Vixen.Application/VixenApplication.cs
* Fix the small memory leak where the graphics and brushes are not properly disposed. Use static color brushes to avoid having to dispose them.
* Adjust the alignment of the development and test build number text to the left so they are not cut off.
> VIX-3608 Fix small memory leak

- sandbox/README.md
- sandbox/sandbox.wsb
- sandbox/scripts/startup.bat
* Add the basic sandbox configuration to allow a developer to launch and install Vixen into for localized testing.
* Provide README with basic instructions to help underdtand how to use it.
> VIX-3609 Add a windows sandbox configuration

- src/Vixen.Common/ffmpeg/ffmpeg.cs
- src/Vixen.Modules/Effect/Video/Video.cs
Long Video effect drifts out of sync when (1000 / Update Interval) is not an integer
> VIX-3611 Long Video effect drifts out of sync

- src/Vixen.Application/Setup/SetupPatchingSimple.Designer.cs
- src/Vixen.Application/Setup/SetupPatchingSimple.cs
- src/Vixen.Application/Setup/SetupPatchingSimple.resx
* When a label wraps to multiline it needs the width constrained in order for the table layout to resize.
* Add logic to constrain the width of the labels to the column width of the table layout.
> VIX-3619 Fix resize issue on long controller name

- src/Vixen.Modules/Effect/Chase/Chase.cs
- src/Vixen.Modules/Effect/Spin/Spin.cs
* Add logic in the UpdateTargetingAttributes methods to detect if the depth is to shallow for the Individual targeting and correct the selection to Group.
> VIX-3628 Fix Behavior targeting bug on the Chase and Spin Effect

- src/Vixen.Modules/Effect/Alternating/Alternating.cs
- src/Vixen.Modules/Effect/Wipe/WipeModule.cs
* Add logic to remove duplicate leaf elements in case the effect is placed on a very deep level prop with multiple redefinition groups.
> VIX-3631 Fix duplicate node rendering in Wipe and Alternate

- src/Vixen.Modules/Preview/VixenPreview/Shapes/PreviewLightBaseShape.cs
- src/Vixen.Modules/Preview/VixenPreview/VixenPreviewControl.cs
- src/Vixen.Modules/Preview/VixenPreview/VixenPreviewSetup3.cs
* Add logic to the node filter to also test for null elements. This will prevent the preview update from seeing invalid links as well as unmapped nodes.
* Add logic and a warning dialog to alert the user of invalid links. Give them the option to cancel and go fix them.
* Highlight the display items that have invalid links when the user is alerted to help them find them quickly.
> VIX-3636 Fix preview crash due to invalid element links

- src/Vixen.Modules/Effect/Fixture/FixtureEffect/Data/FixtureFunctionData.cs
- src/Vixen.Modules/Effect/Fixture/FixtureEffect/FixtureModule.cs
* Add missing Color property to the data class.
* Add logic to update and retrive the value from the data object.
* Add OnDeserialized logic to ensure the Color property is populated on existing sequences.
> VIX-3640 Fix issue with Color not saving on the Fixture Effect

- src/Vixen.Application/OptionsDialog.Designer.cs
- src/Vixen.Application/OptionsDialog.cs
- src/Vixen.Application/OptionsDialog.resx
- src/Vixen.Common/ffmpeg/ffmpeg.cs
- src/Vixen.Core/IO/Policy/SystemConfigFilePolicy.cs
- src/Vixen.Core/IO/Xml/SystemConfig/XmlSystemConfigFilePolicy.cs
- src/Vixen.Core/Module/Effect/EffectModuleInstanceBase.cs
- src/Vixen.Core/Module/Effect/IEffectModuleInstance.cs
- src/Vixen.Core/Sys/SystemConfig.cs
- src/Vixen.Core/Sys/VixenSystem.cs
- src/Vixen.Modules/Editor/TimedSequenceEditor/TimedSequenceEditorForm.cs
- src/Vixen.Modules/Effect/Video/Video.cs
- src/Vixen.Modules/Effect/Video/VideoData.cs
VIX-3625 Video Effect Cache Improvements
- Changed the cache folder model from InstanceID based to Settings Hash base with an associating file - In VideoEffect temp folder, (InstanceID).(Settings Hash)
- This allows the same settings to build or use the same cache folder, so multiple effects can use the same cache folder too
- Used MD5 to create the hash so it is consistent between executions of the application
- Added new GetVideoDurationAndResolution function that doesn't use the cache folder and gets both in a single run of ffmpeg
- Refactored Video.cs:GetVideoInformation to use GetVideoDurationAndResolution
- Added a Removing method to allow TimedSequenceEditorForm to let an Effect know when it has been deleted
- Updated Dispose method to clean up cache folder
- Used path functions in …
> VIX-3625 Video Effect Cache Improvements

- src/Vixen.Modules/Preview/VixenPreview/Shapes/PreviewLightBaseShape.cs
VIX-3661 Prevent VAO from showing up in shape property settings
> VIX-3661 Prevent VAO from showing up in shape property settings

- src/Vixen.Application/Vixen.Application.csproj
- src/Vixen.Common/WpfPropertyGrid.Themes/WpfPropertyGrid.Themes.csproj
- src/Vixen.Common/WpfPropertyGrid/WpfPropertyGrid.csproj
- src/Vixen.Modules/App/CustomPropEditor/CustomPropEditor.csproj
- src/Vixen.Modules/App/TimingTrackBrowser/TimingTrackBrowser.csproj
- src/Vixen.Modules/Editor/TimedSequenceEditor/TimedSequenceEditor.csproj
- src/Vixen.Modules/Preview/VixenPreview/VixenPreview.csproj
* This will clear the vulnerability and stop the Dependabot from reporting.
> Bump MessagePack library to latest 2.5.x to clear vulnerability

- src/Vixen.Common/WPFCommon/Services/DownloadService.cs
* The logic that initializes modified time for comparison should specify it is a UTC time in order to accomodate timezones > UTC
* Logic change based on info found on stackoverflow.
> VIX-3664 Fix modified time logic to specify UTC

- src/Vixen.Modules/App/CustomPropEditor/ViewModels/DrawingPanelViewModel.cs
- src/Vixen.Modules/App/CustomPropEditor/ViewModels/ElementModelViewModel.cs
1) Added a new field, "Light Size" in the property window - tab: Element Info 
2) If the highlighted group contains more than a single light size, then the field shows, "multiple sizes"
> VIX-3117 Show the light size for a custom prop.

- src/Vixen.Modules/Effect/Text/Text.cs
- src/Vixen.Modules/Effect/Text/TextData.cs
- src/Vixen.Modules/EffectEditor/EffectDescriptorAttributes/EffectDescriptionDescriptors.resx
- src/Vixen.Modules/EffectEditor/EffectDescriptorAttributes/EffectDisplayNameDescriptors.resx
Stops scrolling when the text reaches the end. This option is exclusive of the existing option, "Center Stop".
> VIX-3124 Added "End Stop" option to Text Effect 

- Directory.Packages.props
- src/Vixen.DeployBundle/Vixen.DeployBundle.wixproj
- src/Vixen.Installer/Vixen.Installer.wixproj
Patches an issue with the installer and deploy projects that were missing the PackageReferences.
> Patch to fix missing PackageReferences in the Deploy - Installer projects

- src/Vixen.Core/Sys/Props/BaseProp.cs
- src/Vixen.Modules/App/Props/Models/Arch/Arch.cs
- src/Vixen.Modules/App/Props/Models/BaseLightProp.cs
- src/Vixen.Modules/App/Props/Models/Tree/Tree.cs
* Added xml docs to most all of the methods and properties so other developers have a better idea of what they do.
* Refactor the GetOrCreateElementNode variables to be more descriptive. Considered renaming the method itself, but do not want to break existing work by other devs.
* Added PropModified method to update the modified date time so implementors can call it instead of writing their own.
> VIX-3712 Refactor to update documentation and variable names in the Prop classes

- src/Vixen.Application/Setup/DisplaySetup.cs
- src/Vixen.Common/Controls/ControllerTree.cs
- src/Vixen.Core/Sys/Managers/OutputControllerManager.cs
* Add logic to maintain the state of the controllers when they are reordered in the mediator.
* Change the sort order logic to use the controller id over the controller name as the key to ensure the proper order.
* TODO The logic should really maintain whether the controller order actually changed and avoid the arbitrary reorder each time the setup is closed.
> VIX-3723 Fix controller stop bug
