VixenLights/Vixen

Modules/Output/E1.31/SetupForm.cs

Scroll SACN universe list to newly created universe when using the add universe button.

Scroll SACN universe list to newly created universe

---

Modules/App/CustomPropEditor/ViewModels/PropEditorViewModel.cs

Consolidate the logic that imports from the vendor and from the menu item to use the same logic path for the actual import. This allows this logic to be contained into one place. It also resolves having a consistent busy icon from both paths and error trapping.

VIX-2784 Add logic to switch to selection mode after imports.

---

Application/VixenApplication/Setup/ElementTemplates/Arch.cs
Application/VixenApplication/Setup/ElementTemplates/CandyCane.cs
Application/VixenApplication/Setup/ElementTemplates/NumberedGroup.cs
Application/VixenApplication/Setup/ElementTemplates/Star.cs
Application/VixenApplication/VixenApplication.csproj

Enhance the NumberedGroup to allow it to easily be extended and create new types that wrap it. Added the 3 new types.

VIX-2790 Create quick templates for Arch, Candy Cane and Star.

---

Modules/App/Curves/CurveEditor.cs

The text box tries to ensure non numeric values are entered, but there a times that the right series of events can get past it. Change the parsing logic to handle it and not crash if it gets unexpected values.

VIX-2793 Change the logic that parses the text to be more resilient.

---

Modules/Effect/Bars/Bars.cs

The Right, Down, Expand, Alternate Down, Horizontal Compress, Alternate Right had logic errors in them that caused colors to occupy two bars part of the time. It would cause a flicker. Adjust the logic to calculate the colors correctly.
The other movements in locations were not in sync with the same movements in the strings option, so switching between them was significantly different at times. Corrected the faulty color logic on those.
The color gradients did not work at all due to a math rounding error. Fixed this across strings and locations.

VIX-2813 VIX-2641 Fix multiple issues with the Bars effect.

---

Modules/Editor/TimedSequenceEditor/TimedSequenceEditorForm_Toolstrip.cs

I suspect the issue was coming with the save portion that was trying to gather all the state of the toolbars when closing. There was logic that set the whole toolbar visible if it was not to try and get its child items visible state. My theory is that causes layout inconsistencies and may lead to false values for visible. We are already updating the state on the fly when it changes except for the effects. I added the effects to that live update and then the state gathering at close is no longer required. This allows us to just save it. Less chance for issues to occur.
Cleaned up the PopulateToolStripStates method to only handle the initial population. This is probably not even necessary because the states will be updated as they are changed and if the state is not present it defaults to …

VIX-2811 Part two on attempts to fix ghost tool buttons.

---

Modules/App/SuperScheduler/ScheduleItem.cs

The management of running actions occurs in a threaded environment and if the right combination of sequences ending at the same time can cause an index out of range when the running actions are removed.

VIX-2880 Fix the threading issue causing crashes.

---

Modules/Property/Order/OrderSetupHelper.cs

Added a zigzag option to patching order helper. This isn't the grand plan that I had in mind for this ticket but it's zigzag nonetheless.

Add zigzag patching option to patching order helper.

---

Modules/Editor/EffectEditor/Controls/BaseInlineCurveEditor.cs

The root of this tickets issue is not with the pinwheel itself, but with a generic error that happens in the mouse move handler in the curve editor. This appears in other effects and seems to manifest with the right series of events that cause some object to be null in the method. I suspect this is the curve itself being replaced but the log traces so far have not be specific enough. This adds logic to trap and eat the exception if it occurs to prevent the app from crashing. This method is called numerous times in a editing fashion and will likely recover just fine if it does not execute completely.

VIX-2601 Add exception handling onto the curve mouse handler.

---

.github/workflows/compile_test.yml
.github/workflows/release_build.yml
Build/CreateReleaseNotes.ps1

Implements workflows for release builds on tag/release to master and compile tests on pull requests to master.
These steps should be completed prior to merge:
- Disable builds in TeamCity
- Development Build
- Release Build
- Vixenlights Pull Request Development Build
- Tag master with "build-number-NNN" where NNN is the latest build number (currently 962)
- Set repo secrets detailed in release_build.yml lines 253 - 258

VIX-2916 Implement GitHub Actions workflow

---

Modules/App/ExportWizard/BulkExportOutputFormatStage.Designer.cs
Modules/App/ExportWizard/BulkExportOutputFormatStage.cs
Modules/Editor/TimedSequenceEditor/ExportDialog.Designer.cs
Modules/Editor/TimedSequenceEditor/ExportDialog.cs

Enhance both the single export and the bulk export wizard to allow the user to type in a custom timing interval into the combo box. The export wizard will save the entered value if the user saves the profile. The single export will not.

VIX-2924 Add feature to allow custom export resolutions.

---

Vixen.System/IO/Xml/XElementFileWriter.cs

Prior to this the backups were made by copying the file to a new version. This could be corrupted also, so this will just attempt a move which should be a simple rename at the OS level and hopefully simpler. The backups will be named with a time stamp and purged once there are more than 3 to maintain the 3 backups. If corruption is detected, the backups will be renamed to the protected names so they do not get overwritten.

VIX-2929 Improve how backups are kept when the user saves changes.

---

Modules/Preview/VixenPreview/OpenGL/OpenGLPreviewForm.cs

Updated the logic to prevent getting stuck zoomed out of the limits.

VIX-2932 Preview Zoom Got Stuck

---

Common/Controls/TimeLineControl/Grid.cs

The events and information to determine if alignment marks are needed already existed, so added the logic to draw them in the timeline.

VIX-2974 Add alignment marks to the end of the marks that have length.

---

Vixen.System/Export/FSEQCompressedWriter.cs

Rounding errors were causing an off by one error in the block size calculation.

VIX-2983 Fix rounding errors in the compressed export.

---

Build/CreateReleaseNotes.ps1

set-env has been deprecated in github actions.

Update the release notes script to remove set-env.

---

Common/Controls/TextProgressBar.cs

The TextProgressbar uses a rendering method that requires visual styles to be supported. Add logic to gracefully degrade if they are not.

VIX-3031 Play nice with systems that have visual styles turned off.

---

Modules/Effect/Bars/Bars.cs
Modules/Effect/Bars/Bars.csproj
Modules/Effect/Bars/BarsData.cs
Modules/EffectEditor/EffectDescriptorAttributes/EffectDescriptionDescriptors.resx
Modules/EffectEditor/EffectDescriptorAttributes/EffectDisplayNameDescriptors.resx

VIX-3033 Adding Rotation to the Bars Effect

VIX-3033 Adding Rotation to the Bars Effect

---

Modules/Effect/Picture/Picture.cs
Modules/Effect/Picture/PictureData.cs
Modules/EffectEditor/EffectDescriptorAttributes/EffectDescriptionDescriptors.resx
Modules/EffectEditor/EffectDescriptorAttributes/EffectDisplayNameDescriptors.resx

VIX-3053 Add "Center Stop" to Picture Effect

VIX-3053 Add "Center Stop" to Picture Effect

---

Modules/Effect/Picture/Picture.cs

VIX-3084 Fixing bug with image movement up and down

VIX-3084 Fixing bug with image with movement up and down

---

Common/Controls/ColorPicker/ColorPicker.cs

Added Icon to color picker form.

Added Vixen icon to color picker form.

---

Modules/PostFilter/ColorBreakdown/ColorBreakdownSetup.Designer.cs
Modules/PostFilter/ColorBreakdown/ColorBreakdownSetup.cs

Added Icon to color picker form.

Added Vixen icon to Color Breakdown form.

---

Common/Controls/TimeLineControl/MarksBar.cs

Modified so that menu item separator only appears if needed.

VIX-3037 Modified context menu for mark bar

---

Modules/App/CustomPropEditor/Import/XLights/XModelImport.cs

Add logic to handle ranges that decrement as well as increment.

VIX-3108 Fix improper range logic.

---

Modules/Effect/Liquid/Liquid/LiquidData.cs

There was an indexing logic error in LiquidData.cs CreateInstanceForClone method.

VIX-3143 Fixing Liquid Effect Ctrl Copy crashing Vixen

---

Common/Controls/ElementTree.cs

Refactor to common logic to enable menu items when proper pasting can occur.
Fix logic that checks if you can paste as new.

VIX-3151 Add logic to prevent pasting as new in a recursive way.

---

Modules/Editor/TimedSequenceEditor/EffectTimeEditor.Designer.cs
Modules/Editor/TimedSequenceEditor/EffectTimeEditor.cs

Added a new label and button to the Effect Time Editor form to allow the user to set the times to sequence start / End.
Add logic to handle setting the times as needed.

VIX-3129 Add ability to set the effect time to the entire sequence.

---

Common/Controls/Theme/ThemeGroupBoxRenderer.cs

This error is random and pretty rare, but when the unknown condition exists, it can cause a fatal crash. This logic will attempt to catch and log the issue in hopes of preventing a crash that could cause corruption.

VIX-2962 Add exception handling logic to try and prevent a had crash.

---

Vixen.System/Module/ModuleDataModelBase.cs

Removing the element versions breaks the sequences. Need to find a different way to solve this.

VIX-3172 Fix serializer issue introduced with VIX-3148

---

Vixen.System/Commands/FixtureIndexType.cs
Vixen.System/Commands/Named8BitCommand.cs

New command type to support intelligent fixtures.

VIX-3178 Created Named8BitCommand to support Intelligent Fixtures

---

Modules/PostFilter/TaggedFilter/TaggedFilter.csproj

Unused Fixture.csproj project reference.

VIX-3184 Unused project references in taggedFilter.csproj

---

Modules/Property/Color/ColorSetsSetupForm.Designer.cs

VIX-3100 Allow color Property to support more than 8 Discrete Colors

VIX-3100 Allow color Property to support more than 8 Discrete Colors

---

Modules/App/FixtureSpecificationManager/FixtureSpecificationManager.cs
Modules/App/FixtureSpecificationManager/IFixtureSpecificationManager.cs

VIX-3198 Add Gobo Images to the Fixture Specification Manager

VIX-3198 Add Gobo Images to the Fixture Specification Manager

---

Modules/Property/Order/OrderSetupHelper.cs

Improve the performance of the zig zag operation by changing it around to directly manipulate the order instead of using a temporary dictionary. Wrap it in begin and end updates to improve the UI rendering speed.
Add logic to support Ctrl-A selection of all the elements in the list view for those that want to apply the reverse or zig zag logic to all elements.

VIX-3208 Improvements.

---

Modules/Editor/TimedSequenceEditor/Forms/Form_Effects.Designer.cs
Modules/Editor/TimedSequenceEditor/Forms/Form_Effects.cs
Modules/Editor/TimedSequenceEditor/TimedSequenceEditorForm.Designer.cs
Modules/Editor/TimedSequenceEditor/TimedSequenceEditorForm_Toolstrip.cs
Vixen.System/Module/Effect/EffectModuleDescriptorBase.cs

VIX-3202 Add 'Intelligent Fixture' group in the Effects tree

VIX-3202 Add 'Intelligent Fixture' group in the Effects tree

---

Modules/PostFilter/ColorWheelFilter/Filters/ColorWheelFilter.cs
Modules/PostFilter/ColorWheelFilter/Outputs/ColorWheelFilterOutput.cs

VIX-3206 Update Color Wheel Filter to better follow the dispatch pattern

VIX-3206 Update Color Wheel Filter to better follow the dispatch pattern

---

Modules/PostFilter/ShutterFilter/Filter/ShutterFilter.cs
Modules/PostFilter/ShutterFilter/Output/ShuttterFilterOutput.cs

VIX-3207 Update Shutter filter to handle spinning color wheels and driving the color wheel directly

VIX-3207 Update Shutter filter to handle spinning color wheels and driving color wheel directly

---

Modules/Editor/EffectEditor/Controls/CollectionView.cs
Modules/Editor/EffectEditor/PropertyItemValue.cs
Modules/Effect/Effect/ExpandoObjectObservableCollection.cs
Modules/Effect/Effect/IDiscoverCollectionType.cs
Modules/Effect/Effect/IExpandoObjectCollection.cs
Modules/Effect/Effect/MarkCollectionExpandoObjectCollection.cs
Modules/Effect/Liquid/Emitter/IEmitter.cs
Modules/Effect/Liquid/Liquid/EmitterCollection.cs
Modules/Effect/Wave/Wave/WaveFormCollection.cs

VIX-3190 Effect Editor does not support empty collections

VIX-3190 Effect Editor does not support empty collections

---

Modules/EffectEditor/EffectDescriptorAttributes/EffectDescriptionDescriptors.resx
Modules/EffectEditor/EffectDescriptorAttributes/EffectDisplayNameDescriptors.resx

VIX-3199 Intelligent Fixture Strobe Effect localization descriptors

VIX-3199 Intelligent Fixture Strobe Effect localization descriptors

---

Modules/Editor/FixturePropertyEditor/Views/FixturePropertyEditorWindowView.xaml
Modules/Editor/FixturePropertyEditor/Views/FunctionTypeWindowView.xaml

VIX-3226 Remove Catel InfoBar from Fixture Property Editor views

VIX-3226 Remove Catel InfoBar from Fixture Property Editor views

---

Modules/Editor/FixturePropertyEditor/Views/ColorWheelView.xaml

VIX-3228 Fixture Property Editor - Color Wheel Grid contains binding copy/paste error

VIX-3228 Fixture Property Editor - Color Wheel Grid contains binding copy/paste error

---

Modules/PostFilter/TaggedFilter/TaggedFilterModule.cs
Modules/PostFilter/TaggedFilter/TaggedFilterModuleBase.cs
Modules/PostFilter/TaggedFilter/TaggedFilterSetup.cs

VIX-3232 Move Tagged Filter Setup dialog to base class

VIX-3232 Move Tagged Filter Setup dialog to base class

---

Modules/Editor/FixturePropertyEditor/ViewModels/FixturePropertyEditorViewModel.cs

VIX-3220 Fixture Channel numbers do not compress when deleting channels

VIX-3220 Fixture Channel numbers do not compress when deleting channels

---

Modules/Editor/EffectEditor/Themes/EditorResources.xaml

VIX-3234 Missing XAML converter ColorToSolidColorBrush_ValueConverter

VIX-3234 Missing XAML converter ColorToSolidColorBrush_ValueConverter

---

Modules/PostFilter/ColorWheelFilter/Filters/ColorWheelFilter.cs

VIX-3227 ColorWheelFilter discrete handler using FullColor vs Color

VIX-3227 ColorWheelFilter discrete handler using FullColor vs Color

---

Modules/App/FixtureSpecificationManager/FixtureSpecificationManager.cs

VIX-3239 Saving Intelligent Fixture is not updating in memory cache of fixtures

VIX-3239 Saving Intelligent Fixture is not updating in memory cache of fixtures

---

Modules/PostFilter/CoarseFineFilter/CoarseFineByteBreakDownOutput.cs

VIX-3240 Add null check to CoarseFineByteBreakDownOutput

VIX-3240 Add null check to CoarseFineByteBreakDownOutput

---

Modules/Editor/FixturePropertyEditor/Views/ColorWheelView.xaml

VIX-3241 ColorWheelView.xaml has extra binding validation rule tags

VIX-3241 ColorWheelView.xaml has extra binding validation rule tags

---

Application/VixenApplication/VixenApplication.cs
Modules/App/FixtureSpecificationManager/FixtureSpecificationManager.cs
Modules/App/FixtureSpecificationManager/IFixtureSpecificationManager.cs

VIX-3233 Initialize FixtureSpecificationManager with Vixen profile path

VIX-3233 Initialize FixtureSpecificationManager with Vixen profile path

---

Application/VixenApplication/Setup/SetupElementsTree.cs
Modules/Preview/VixenPreview/VixenPreviewSetupElementsDocument.cs

…eously
VIX-3245 Possible to display two Intelligent Fixture Wizards simultaneously

VIX-3245 Possible to display two Intelligent Fixture Wizards simultaneously

---

Application/VixenApplication/Setup/ElementTemplates/IntelligentFixtureTemplate.cs

VIX-3244 Intelligent Fixture Group was associated with an element node

VIX-3244 Intelligent Fixture Group was associated with an element node

---

Modules/App/FixtureSpecificationManager/FixtureSpecificationManager.cs

VIX-3246 Intelligent Fixture Wizard - Add the ability to clear out a gobo image

VIX-3246 Intelligent Fixture Wizard - Add the ability to clear out a gobo image

---

Modules/Editor/FixturePropertyEditor/ViewModels/FunctionTypeViewModel.cs
Modules/Effect/Effect/ExpandoObjectObservableCollection.cs

VIX-3247 Comment Cleanup

---

Modules/Editor/FixturePropertyEditor/ViewModels/FunctionTypeViewModel.cs

VIX-3248 Possible Null Exception displaying Fixture Function Editor

VIX-3248 Possible Null Exception displaying Fixture Function Editor

---

Modules/Editor/FixturePropertyEditor/ViewModels/FunctionItemViewModel.cs

VIX-3250 Fixture Function Tag drop down is not consistently populating

VIX-3250 Fixture Function Tag drop down is not consistently populating

---

Modules/Editor/FixturePropertyEditor/ViewModels/ItemsViewModel.cs

Intelligent Fixture Editors - Deleting incomplete rows may crash

VIX-3257 Intelligent Fixture Editors - Deleting incomplete rows may crash

---

Modules/Editor/FixtureGraphics/OpenGL/MovingHeadOpenGL.cs
Modules/Preview/VixenPreview/Shapes/MovingHeadIntentHandler.cs

VIX-3261 Intelligent Fixture Preview - Is remembering what beam color was last displayed

VIX-3261 Intelligent Fixture Preview - Is remembering what beam color was last displayed

---

Modules/Editor/FixturePropertyEditor/ViewModels/FunctionTypeViewModel.cs

VIX-3267 Intelligent Fixture Editors does not prevent the user from deleting the None Function

VIX-3267 Intelligent Fixture Editors does not prevent the user from deleting the None Function

---

Modules/App/Fixture/FixtureColorWheel.cs

VIX-3263 Intelligent Fixture Color Wheel Function not working properly with Fixture Effect and Preview

VIX-3263 Intelligent Fixture Color Wheel Function not working properly with Fixture Effect and Preview

---

Modules/App/ElementTemplateHelper/ElementTemplateHelper.cs

VIX-3259 Intelligent Fixture Wizard - If an exception occurs Wizard is left in unknown zombie state

VIX-3259 Intelligent Fixture Wizard - If an exception occurs Wizard is left in unknown zombie state

---

Modules/Editor/FixturePropertyEditor/ViewModels/ItemsViewModel.cs
Modules/Editor/FixturePropertyEditor/Views/ColorWheelView.xaml
Modules/Editor/FixturePropertyEditor/Views/ColorWheelView.xaml.cs
Modules/Editor/FixturePropertyEditor/Views/FixturePropertyEditorView.xaml
Modules/Editor/FixturePropertyEditor/Views/FixturePropertyEditorView.xaml.cs
Modules/Editor/FixturePropertyEditor/Views/FunctionTypeView.xaml
Modules/Editor/FixturePropertyEditor/Views/FunctionTypeView.xaml.cs
Modules/Editor/FixturePropertyEditor/Views/IndexedView.xaml
Modules/Editor/FixturePropertyEditor/Views/IndexedView.xaml.cs
Modules/Editor/FixturePropertyEditor/Views/VixenDataGrid.cs

VIX-3258 Intelligent Fixture Editors - Allow the user to create multiple incomplete rows

VIX-3258 Intelligent Fixture Editors - Allow the user to create multiple incomplete rows

---

Modules/Editor/FixturePropertyEditor/ViewModels/ItemsViewModel.cs
Modules/Editor/FixturePropertyEditor/Views/ColorWheelView.xaml.cs
Modules/Editor/FixturePropertyEditor/Views/FunctionTypeView.xaml.cs
Modules/Editor/FixturePropertyEditor/Views/IndexedView.xaml.cs

VIX-3253 Intelligent Fixture Editors add logic to move focus to the first editable field on the Add Plus button

VIX-3253 Intelligent Fixture Editors add logic to move focus to the first editable field on the Add Plus button

---

Modules/Editor/FixtureGraphics/Geometry/IMovingHeadGeometryConstants.cs
Modules/Editor/FixtureGraphics/Geometry/MovingHeadGeometryConstants.cs
Modules/Editor/FixtureGraphics/IMovingHead.cs
Modules/Editor/FixtureGraphics/MovingHeadSettings.cs
Modules/Editor/FixtureGraphics/OpenGL/IRenderMovingHeadOpenGL.cs
Modules/Editor/FixtureGraphics/OpenGL/MovingHeadOpenGL.cs
Modules/Editor/FixtureGraphics/WPF/MovingHeadWPF.cs
Modules/Preview/VixenPreview/Shapes/MovingHeadIntentHandler.cs
Modules/Preview/VixenPreview/Shapes/PreviewMovingHead.cs

VIX-3249 VIX-3249 Add the ability to mount intelligent fixture upside down

VIX-3249 Add the ability to mount intelligent fixture upside down

---

Common/AudioPlayer/CoreAudioPlayer.cs

* Cache the wavesource from the source to get to a stable version of a wavesource that can produce consistent results when starting and positioning within the audio track.
* Change to initialize the sample into the sound output when played instead of reusing the initial one. This removes a small remaining pop upon replay.

VIX-3270 Fix audio glitch when resuming play.

---

Modules/Editor/FixturePropertyEditor/ViewModels/ChannelItemViewModel.cs

VIX-3281 Intelligent Fixture Wizard - Users cannot easily fix incomplete functions after selecting one on the Edit Channel page

VIX-3281 Intelligent Fixture Wizard - Users cannot easily fix incomplete functions after selecting one on the Edit Channel page

---

Modules/Effect/Effect/EffectListTypeConverterBase.cs
Modules/Effect/Fixture/Fixture/Converters/ColorIndexConverter.cs
Modules/Effect/Fixture/Fixture/Converters/FixtureIndexConverter.cs
Modules/Effect/Fixture/Fixture/Converters/FunctionCollectionNameConverter.cs
Modules/Effect/FixtureStrobe/Converters/FixtureStrobeFixtureIndexConverter.cs
Modules/Effect/FixtureStrobe/Converters/FixtureStrobeFunctionNameConverter.cs
Modules/Effect/Frost/Converters/FrostFunctionNameConverter.cs
Modules/Effect/Gobo/Converters/GoboFixtureIndexConverter.cs
Modules/Effect/Gobo/Converters/GoboFunctionNameConverter.cs
Modules/Effect/Prism/Converters/PrismFixtureIndexConverter.cs
Modules/Effect/Prism/Converters/PrismFunctionNameConverter.cs
Modules/Effect/SpinColorWheel/Converters/SpinColorWheelFixtureIndexConverter.cs
Modules/Effect/SpinColorWheel/Converters/SpinColorWheelFunctionNameConverter.cs

VIX-3280 Update Intelligent Fixture Effects converters to handle when more than one effect instance is selected

VIX-3280 Update Intelligent Fixture Effects converters to handle when more than one effect instance is selected

---

Modules/Editor/FixturePropertyEditor/ViewModels/FunctionTypeViewModel.cs

VIX-3282 Intelligent Fixture Wizard and Editors - Do not show 'None' function on the Edit Functions grid

VIX-3282 Intelligent Fixture Wizard and Editors - Do not show 'None' function on the Edit Functions grid

---

Modules/Preview/VixenPreview/Shapes/MovingHeadIntentHandler.cs

VIX-3283 Intelligent Fixture - Display color wheel half steps as white

VIX-3283 Intelligent Fixture - Display color wheel half steps as white

---

Modules/Preview/VixenPreview/Shapes/MovingHeadIntentHandler.cs

VIX-3300 Fixture Effect direct drive of the color wheel is not opening the shutter

VIX-3300 Fixture Effect direct drive of the color wheel is not opening the shutter

---

Modules/Effect/Fixture/Fixture/FixtureFunctionExpando.cs
Modules/Effect/Fixture/Fixture/FixtureModule.cs

VIX-3293 Fixture Effect has some linq queries that prevent it from working at the group level

VIX-3293 Fixture Effect has some linq queries that prevent it from working at the group level

---

Modules/PostFilter/ColorBreakdown/ColorBreakdownMixingFilterBase.cs

VIX-3294 ColorBreakdownFilter has a memory

VIX-3294 ColorBreakdownFilter has a memory

---

Modules/Effect/Fixture/Fixture/FixtureModule.cs

VIX-3293 Resolving review comments; adding defensive code

VIX-3293 Resolving review comments; adding defensive code

---

Modules/Editor/FixturePropertyEditor/ViewModels/FunctionItemViewModel.cs
Modules/Editor/FixturePropertyEditor/ViewModels/FunctionTypeViewModel.cs
Modules/Editor/FixturePropertyEditor/Views/FunctionTypeView.xaml

VIX-3302 Intelligent Fixture Editors - Remove 'None' from the type drop down

 VIX-3302 Intelligent Fixture Editors - Remove 'None' from the type drop down

---

Modules/Preview/VixenPreview/SelectionDialog/SelectFixtureNodeView.cs
Modules/Preview/VixenPreview/SelectionDialog/SelectFixtureNodeView.xaml
Modules/Preview/VixenPreview/SelectionDialog/SelectFixtureNodeViewModel.cs
Modules/Preview/VixenPreview/Shapes/PreviewMovingHead.cs
Modules/Preview/VixenPreview/Shapes/PreviewSetFixtureElementUIEditor.cs
Modules/Preview/VixenPreview/VixenPreview.csproj

VIX-3298 Intelligent Fixture Preview - Provide better support for linking and unlinking the graphics from an element node

VIX-3298 Intelligent Fixture Preview - Provide better support for linking and unlinking the graphics from an element node

---

Modules/Preview/VixenPreview/Shapes/PreviewMovingHead.cs

VIX-3296 Intelligent Fixture Preview - Need to update color based on whether the graphic is connected to a node

VIX-3296 Intelligent Fixture Preview - Need to update color based on whether the graphic is connected to a node

---

Application/VixenApplication/Setup/ElementTemplates/ElementTemplateBase.cs
Application/VixenApplication/Setup/ElementTemplates/IntelligentFixtureTemplate.cs
Application/VixenApplication/Setup/ElementTemplates/SingleItem.cs
Modules/Preview/VixenPreview/VixenPreviewControl.cs
Vixen.System/Rule/IElementTemplate.cs

VIX-3297 Intelligent Fixture Preview can only create one fixture graphic at a time

VIX-3297 Intelligent Fixture Preview can only create one fixture graphic at a time

---

Common/Controls/ElementTree.cs
Vixen.System/Sys/PropertyManager.cs

VIX-3295 Update 'Paste As New' to copy properties associated with the source node(s)

VIX-3295 Update 'Paste As New' to copy properties associated with the source node(s)

---

Modules/Effect/Effect/FixtureEffectBase.cs
Modules/Effect/Fixture/Fixture/FixtureModule.cs
Modules/PostFilter/DimmingCurve/DimmingCurveModule.cs
Modules/PostFilter/DimmingFilter/Filters/DimmingFilter.cs
Modules/Preview/VixenPreview/Shapes/MovingHeadIntentHandler.cs
Vixen.System/Data/Value/RangeValue.cs
Vixen.System/Interpolator/RangeValueInterpolator.cs

VIX-3266 Add Intelligent Fixture Legend Support for Color Wheel and Range functions

VIX-3266 Add Intelligent Fixture Legend Support for Color Wheel and Range functions

---

Modules/Preview/VixenPreview/Shapes/PreviewMovingHead.cs

VIX-3310 - Cleanup Intelligent Fixture Preview Descriptions

VIX-3310 - Cleanup Intelligent Fixture Preview Descriptions

---

Modules/App/FixtureSpecificationManager/FixtureSpecificationManager.cs
Modules/App/FixtureSpecificationManager/FixtureSpecificationManager.csproj

VIX-3317 Add logic Fixture Specification Manager to handle duplicate fixture names

VIX-3317 Add logic Fixture Specification Manager to handle duplicate fixture names

---

Modules/Editor/FixtureWizard/Wizard/Models/SelectProfileWizardPage.cs
Modules/Editor/FixtureWizard/Wizard/ViewModels/SelectProfileWizardPageViewModel.cs
Modules/Editor/FixtureWizard/Wizard/Views/SelectProfileWizardPageView.xaml

VIX-3318 Add Enable/Disable logic to Intelligent Fixture Select Profile Wizard Page

VIX-3318 Add Enable/Disable logic to Intelligent Fixture Select Profile Wizard Page

---

Modules/Preview/VixenPreview/VixenPreviewControl.cs
Modules/Preview/VixenPreview/VixenPreviewSetupElementsDocument.cs

VIX-3314 Display Setup and Vixen Preview does not refresh fixtures properly

VIX-3314 Display Setup and Vixen Preview does not refresh fixtures properly

---

Modules/Preview/VixenPreview/Shapes/PreviewIcicle.cs
Modules/Preview/VixenPreview/Shapes/PreviewLightBaseShape.cs
Modules/Preview/VixenPreview/Shapes/PreviewMegaTree.cs
Modules/Preview/VixenPreview/Shapes/PreviewPixelGrid.cs
Modules/Preview/VixenPreview/Shapes/PreviewRectangle.cs
Modules/Preview/VixenPreview/Shapes/PreviewStarBurst.cs
Modules/Preview/VixenPreview/Shapes/PreviewTriangle.cs

VIX-3322 Setup Preview is slow for large displays

VIX-3322 Setup Preview is slow for large displays

---

Modules/Effect/Fixture/Fixture/FixtureModule.cs

VIX-3330 Fixture Effect is not outputing color intents

VIX-3330 Fixture Effect is not outputing color intents

---

Modules/Effect/Fixture/Fixture/FixtureFunctionExpando.cs
Modules/Effect/Fixture/Fixture/FixtureModule.cs
Modules/Effect/Fixture/IFixtureFunctionExpando/IFixtureFunctionExpando.cs
Modules/EffectEditor/EffectDescriptorAttributes/EffectDescriptionDescriptors.resx
Modules/EffectEditor/EffectDescriptorAttributes/EffectDisplayNameDescriptors.resx

VIX-3335 Fixture Effect - Color Selection has a range curve for the Intensity but the label is just "Range"

VIX-3335 Fixture Effect - Color Selection has a range curve for the Intensity but the label is just "Range"

---

Modules/Preview/VixenPreview/Shapes/MovingHeadIntentHandler.cs

VIX-3338 Fixture Preview Not Dimming Correctly

VIX-3338 Fixture Preview Not Dimming Correctly

---

Modules/Preview/VixenPreview/Shapes/PreviewLightBaseShape.cs

VIX-3351 Setup Preview Zoom broken

VIX-3351 Setup Preview Zoom broken

---

Modules/Editor/FixtureGraphics/IMovingHead.cs
Modules/Editor/FixtureGraphics/MovingHeadSettings.cs
Modules/Editor/FixtureGraphics/OpenGL/MovingHeadOpenGL.cs
Modules/Editor/FixtureGraphics/OpenGL/MovingHeadRenderStrategy.cs
Modules/Editor/FixtureGraphics/OpenGL/Shaders/ColorVolumeShader.cs
Modules/Editor/FixtureGraphics/OpenGL/Shaders/ColorVolumeShader1.cs
Modules/Editor/FixtureGraphics/OpenGL/Shaders/ColorVolumeShader2.cs
Modules/Editor/FixtureGraphics/OpenGL/Shaders/GrayVolumeShader.cs
Modules/Editor/FixtureGraphics/OpenGL/Shaders/VolumeShader.cs
Modules/Editor/FixtureGraphics/OpenGL/Volumes/BeamCylinderWithEndCaps.cs
Modules/Editor/FixtureGraphics/OpenGL/Volumes/Cylinder.cs
Modules/Editor/FixtureGraphics/OpenGL/Volumes/CylinderBase.cs
Modules/Editor/FixtureGraphics/OpenGL/Volumes/CylinderWithEndCaps.cs
Modules/Editor/FixtureGraphics/OpenGL/Volumes/IUpdateCylinder.cs
Modules/Editor/FixtureGraphics/OpenGL/Volumes/RotatingCylinderWithEndCaps.cs
Modules/Editor/FixtureGraphics/WPF/MovingHeadWPF.cs
Modules/Editor/FixturePropertyEditor/Views/PanTiltView.xaml.cs
Modules/Editor/FixtureWizard/Wizard/Views/WizardUserControlBase.cs
Modules/Preview/VixenPreview/Shapes/MovingHeadIntentHandler.cs
Modules/Preview/VixenPreview/Shapes/PreviewMovingHead.cs

VIX-3357 Add support for color wheel half step in the Vixen Preview

VIX-3357 Add support for color wheel half step in the Vixen Preview

---

Modules/Effect/Wave/Wave/Wave.cs

VIX-3326 Wave effect does not use the last string in a group

VIX-3326 Wave effect does not use the last string in a group

---

Common/AudioPlayer/AudioOutputManager.cs
Common/AudioPlayer/AudioPlayer.csproj
Common/AudioPlayer/SampleProvider/NVorbisSource.cs
Common/Libraries/Libraries.csproj

Support is provided by the NVorbis library codec. Added logic to add the codec to the factory.

VIX-3358 Add support for Ogg-Vorbis audio files.

---

Modules/Editor/FixtureGraphics/OpenGL/Shaders/ColorVolumeShader1.cs
Modules/Editor/FixtureGraphics/OpenGL/Shaders/ColorVolumeShader2.cs
Modules/Editor/FixtureGraphics/OpenGL/Shaders/GrayVolumeShader.cs
Modules/Editor/FixtureGraphics/OpenGL/Shaders/VolumeShader.cs

VIX-3357 This change was made late in testing and somehow I did not get it in the PR.

VIX-3357 Lost change made late in testing

---

Modules/Effect/Meteor/Meteors.cs
Modules/Effect/Meteor/MeteorsData.cs
Modules/EffectEditor/EffectDescriptorAttributes/EffectDescriptionDescriptors.resx
Modules/EffectEditor/EffectDescriptorAttributes/EffectDisplayNameDescriptors.resx

Added an effect property for an adjustable brightness taper on the meteor's tail.

VIX-3368 Meteor effect enhancements

---

src/Vixen.Common/Box2D/Box2D.vcxproj
src/Vixen.Modules/Analysis/QMLibrary/QMLibrary.vcxproj
src/Vixen.Modules/Effect/Liquid/LiquidFunWrapper/LiquidLiquidFunWrapper.vcxproj

VIX-3373 Update C++ Projects to .NET 6.0 and Visual Studio 2022

VIX-3373 Update C++ Projects to .NET 6.0 and Visual Studio 2022

---

src/Vixen.Modules/Effect/Bars/Bars.cs

VIX-3384 Math/Sizing Error in Bars Effect with Zig Zag Bars in location mode

 VIX-3384 Math/Sizing Error in Bars Effect with Zig Zag Bars in location mode

---

src/Vixen.Modules/Editor/PolygonEditor/PolygonEditor.csproj

VIX-3401 Fixing embedded toolbar buttons
The build action on these items was not set to resource.

VIX-3401 Fixing embedded toolbar buttons

---

src/Vixen.Application/Vixen.Application.csproj

VIX-4310 Removing left over reference to Orc.Wizard project

VIX-4310 Removing left over reference to Orc.Wizard project

---

src/Vixen.Modules/Editor/TimedSequenceEditor/EffectModelCandidate.cs
src/Vixen.Modules/Editor/TimedSequenceEditor/TimedSequenceEditorForm.cs
src/Vixen.Modules/Editor/TimedSequenceEditor/Undo/EffectsModifiedUndoAction.cs

VIX-3385 Fixing copy and paste of effects for .NET Core

VIX-3385 Fixing copy and paste of effects for .NET Core

---

src/Vixen.Common/WPFCommon/Theme/ExpressionDark.xaml
src/Vixen.Common/WPFCommon/Theme/ExpressionDarkBrushes.xaml
src/Vixen.Modules/Editor/FixtureGraphics/FixtureGraphics.csproj
src/Vixen.Modules/Editor/FixturePropertyEditor/FixturePropertyEditor.csproj
src/Vixen.Modules/Editor/FixturePropertyEditor/Views/ColorWheelView.xaml
src/Vixen.Modules/Editor/FixturePropertyEditor/Views/FixturePropertyEditorView.xaml
src/Vixen.Modules/Editor/FixturePropertyEditor/Views/FunctionTypeView.xaml
src/Vixen.Modules/Editor/FixturePropertyEditor/Views/FunctionTypeWindowView.xaml
src/Vixen.Modules/Editor/FixturePropertyEditor/Views/IndexedView.xaml
src/Vixen.Modules/Editor/FixturePropertyEditor/Views/PanTiltView.xaml

The DataGrid Theme package is no longer maintained and does not confirm to .NET 6. Include the necessary theme files into the WPF Common project to remove the dependency on the old library.

VIX-3412 Import the theme files from the outdated DataGrid Theme.

---

src/Vixen.Modules/Analysis/BeatsAndBars/BeatsAndBars.csproj
src/Vixen.Modules/Analysis/QMLibrary/WrapperFiles/ManagedFeature.h
src/Vixen.Modules/Analysis/QMLibrary/WrapperFiles/ManagedOutput.h
src/Vixen.Modules/Analysis/QMLibrary/WrapperFiles/ManagedParameter.h
src/Vixen.Modules/Analysis/QMLibrary/WrapperFiles/ManagedPlugin.cpp

VIX-3414 Removing dependency on STL CLR and getting Beat / Bar Detection to work on .NET core

VIX-3414 Removing dependency on STL CLR and getting Beat / Bar Detection to work on .NET core

---

src/Vixen.Modules/Effect/Liquid/LiquidFunWrapper/LiquidFunWrapper.cpp
src/Vixen.Modules/Effect/Liquid/LiquidFunWrapper/LiquidLiquidFunWrapper.vcxproj

VIX-3415 Cleaning Up Warnings

---

src/Vixen.Modules/Controller/RDSController/Module.cs

* Replaced WebRequest with HttpClient and made the task async to work with the async features of HttpClient.
* Removed excessive logging.

VIX-3422 Replace WebRequest with HttpClient

---

src/Vixen.Modules/Preview/VixenPreview/Shapes/PreviewLightBaseShape.cs

VIX-3423 Removing warnings from a previous refactoring

VIX-3423 Removing warnings from a previous refactoring

---

src/Vixen.Modules/Editor/FixtureWizard/FixtureWizard.csproj
src/Vixen.Modules/Editor/FixtureWizard/FodyWeavers.xml

VIX-3424 Fixing Fody Warnings

---

src/Vixen.Common/Controls/ElementTree.cs
src/Vixen.Common/Controls/Wizard/WizardStage.cs
src/Vixen.Modules/App/CustomPropEditor/ViewModels/PropEditorViewModel.cs
src/Vixen.Modules/App/SuperScheduler/SetupForm.cs
src/Vixen.Modules/App/TimedSequenceMapper/SequencePackageImport/SequencePackageImportInputStage.cs
src/Vixen.Modules/App/WebServer/Service/ContextBroadcaster.cs
src/Vixen.Modules/Preview/VixenPreview/VixenPreviewControl.cs

* Add await operator where appropriate so calls act as intended.
* Remove async modifier on methods that do not involve async operations.

VIX-3425 Resolve async await warnings

---

src/Vixen.Application/GraphicalPatching/ConnectionTool.cs
src/Vixen.Common/Controls/TimeLineControl/RowList.cs
src/Vixen.Common/NShape/Tool.cs
src/Vixen.Core/Services/ElementNodeService.cs
src/Vixen.Core/Sys/ElementNode.cs
src/Vixen.Core/Sys/Managers/ElementManager.cs
src/Vixen.Core/Sys/Managers/NodeManager.cs
src/Vixen.Core/Sys/PropertyManager.cs
src/Vixen.Modules/Preview/VixenPreview/Shapes/PreviewArch.cs

* Removed null checks of non nullable structs in the Preview, Vixen.Application, and NShape projects.
* Added the nullable enabled marker in several of the Vixen.Core classes and resolved nullable issues to make them compliant.

VIX-3427 Resolve nullable and null check warnings.

---

src/Vixen.Core/IO/Binary/SequenceCache/SequenceCacheBinaryReader.cs
src/Vixen.Core/IO/Binary/SequenceCache/SequenceCacheBinaryWriter.cs
src/Vixen.Modules/App/Shows/ObjectCopier.cs

* Replaced with DataContractSerializer,

VIX-3432 Resolve deprecated BinaryFormatter

---

src/Vixen.Common/Controls/ElementTree.cs

* Make the two places that can delete in this control use the same form of message box.

VIX-2859 Ensure the user is asked about deleting elements.

---

src/Vixen.Modules/Effect/CustomValue/CustomValue.cs
src/Vixen.Modules/Effect/Launcher/Module.cs
src/Vixen.Modules/Effect/RDS/RDSModule.cs

* Add links to the docs pages for the custom value, launcher and rds effects.

VIX-3409 Add proper links to the documentation

---

src/Vixen.Modules/Effect/Tree/Tree.cs
src/Vixen.Modules/EffectEditor/EffectDescriptorAttributes/EffectDescriptionDescriptors.resx

VIX-3404 Adding tooltips to the tree effect

VIX-3404 Adding tooltips to the tree effect

---

src/Vixen.DeployBundle/Vixen.DeployBundle.wixproj
src/Vixen.Installer/ExcludeVixenExeFile.xslt
src/Vixen.Installer/Vixen.Installer.wixproj
src/Vixen.Installer/VixenFolders.wxs
src/Vixen.Installer/VixenReleasePackage.wxs

* Add a xslt transform to exclude the main exe from the harvest process
* Update the shortcuts to support advertise which allows for self healing.

VIX-3445 Update installer to support self healing capabilities of msi

---

src/Vixen.Modules/Effect/Fixture/FixtureEffect/Data/FixtureData.cs

Fixing bug with Fixture Effect clone logic.

VIX-3444 Vixen Crash when maniplutating divide at cursor on Fixture effect

---

Vixen.sln
src/Vixen.Modules/Effect/Weave/Weave.cs

VIX-3446 - Add Weave Effect Project to Solution

VIX-3446 - Add Weave Effect Project to Solution

---

src/Vixen.Modules/Effect/Weave/Weave.cs
src/Vixen.Modules/Effect/Weave/WeaveData.cs

VIX-3447 Replacing advanced sizing curves with sliders to avoid jitter

VIX-3447 Replacing advanced sizing curves with sliders to avoid jitter

---

src/Vixen.Modules/Effect/Shockwave/ShockwaveData.cs

…Radius flag
VIX-3456 - ShockwaveData CreateInstanceForClone is not copying ScaledRadius flag

VIX-3456 - ShockwaveData CreateInstanceForClone is not copying ScaledRadius flag

---

src/Vixen.Modules/Effect/Bars/Bars.cs
src/Vixen.Modules/Effect/Weave/Weave.cs

VIX-3459 Fixing Bars and Weave effect rotation bug in location mode

VIX-3459 Fixing Bars and Weave effect rotation bug in location mode

---

src/Vixen.Modules/Property/Location/LocationData.cs

VIX-3460 Adding logic to detect and correct invalid location data

VIX-3460 Adding logic to detect and correct invalid location data

---

src/Vixen.DeployBundle/VCRedistPackage.wxs
src/Vixen.DeployBundle/Vixen.DeployBundle.wixproj
src/Vixen.Installer/Vixen.Installer.wixproj

* Update the version of the VC Redist installer.
* USe the product code to detect if the VC++ is installed as it should be more reliable.

VIX-3468 Fix installer issue with VC Redistributable

---

src/Vixen.Modules/Editor/FixtureWizard/Wizard/Models/ColorSupportWizardPage.cs

VIX-3466 Fixing Color Summary text for when no color option is selected

VIX-3466 Fixing Color Summary text for when no color option is selected

---

src/Vixen.Modules/Editor/FixtureWizard/Wizard/Models/IntelligentFixtureWizard.cs

VIX-3467 Fixing Intelligent Fixture Wizard Clipping

VIX-3467 Fixing Intelligent Fixture Wizard Clipping

---

src/Vixen.Modules/App/CustomPropEditor/Import/XLights/CustomModel.cs
src/Vixen.Modules/App/CustomPropEditor/Import/XLights/Faces/FaceInfo.cs
src/Vixen.Modules/App/CustomPropEditor/Import/XLights/Faces/FaceItem.cs
src/Vixen.Modules/App/CustomPropEditor/Import/XLights/ModelType.cs
src/Vixen.Modules/App/CustomPropEditor/Import/XLights/Ranges/NodeRange.cs
src/Vixen.Modules/App/CustomPropEditor/Import/XLights/Ranges/Range.cs
src/Vixen.Modules/App/CustomPropEditor/Import/XLights/Ranges/RangeGroup.cs
src/Vixen.Modules/App/CustomPropEditor/Import/XLights/StateInfo.cs
src/Vixen.Modules/App/CustomPropEditor/Import/XLights/StateItem.cs
src/Vixen.Modules/App/CustomPropEditor/Import/XLights/SubModel.cs
src/Vixen.Modules/App/CustomPropEditor/Import/XLights/XModelImport.cs
src/Vixen.Modules/App/CustomPropEditor/Import/XLights/XModelInventoryMapper.cs
src/Vixen.Modules/App/CustomPropEditor/Model/ElementModel.cs
src/Vixen.Modules/App/CustomPropEditor/Model/FaceComponent.cs
src/Vixen.Modules/App/CustomPropEditor/Model/FaceDefinition.cs
src/Vixen.Modules/App/CustomPropEditor/Model/StateDefinition.cs
src/Vixen.Modules/App/CustomPropEditor/Services/PropModelPersistenceService.cs
src/Vixen.Modules/App/CustomPropEditor/Services/PropModelServices.cs
src/Vixen.Modules/App/CustomPropEditor/ViewModels/ElementModelViewModel.cs
src/Vixen.Modules/App/CustomPropEditor/ViewModels/PropEditorViewModel.cs

Improve xModel imports including supporting ones that have state. Better Face mapping support as well.

VIX-3346 Improve xModel imports.

---

src/Vixen.Common/Help/Help.cs

VIX-3463 Fixing broken preview help links

VIX-3463 Fixing broken preview help links

---

src/Vixen.Common/Controls/TimeLineControl/MarksBar.cs

* It appears from the user logs that the state object for moving marks was getting nulled out before the other logic could complete. Adding checks in to ensure multiple actions could not occur at the same time. Also localized the logic for the fill gaps double click event to try and prevent that from overlapping. I never could reproduce this locally, so I suspect there is a timing issue that occurs on the end users machine that I cannot recreate.

VIX-3469 Refactor the logic to prevent null exceptions

---

src/Vixen.Application/VixenApplication.Designer.cs
src/Vixen.Application/VixenApplication.cs
src/Vixen.Application/VixenApplication.resx

VIX-2991 Fixing Resizing Logic on main application dialog

VIX-2991 Fixing Resizing Logic on main application dialog

---

src/Vixen.Modules/Effect/Weave/Weave.cs

VIX-3495 Removing test code from Weave Effect

VIX-3495 Removing test code from Weave Effect

---

src/Vixen.Common/Controls/TimeLineControl/Grid.cs
src/Vixen.Common/Controls/TimeLineControl/Row.cs

* Fix leaks in the grid and the row objects.

VIX-3497 Fix memory leak in the editor

---

src/Vixen.Common/AudioPlayer/CoreAudioPlayer.cs

VIX-3500 Fix crash while running show with scheduler

VIX-3500 Fix crash while running show with scheduler

---

src/Vixen.Modules/Effect/Effect/FixtureEffectBase.cs
src/Vixen.Modules/Effect/Fixture/FixtureEffect/FixtureFunctionExpando.cs

VIX-3509 Update Fixture effect to allow duplicate colors

VIX-3509 Update Fixture effect to allow duplicate colors

---

src/Vixen.Modules/Preview/VixenPreview/Shapes/PreviewMovingHead.cs
src/Vixen.Modules/Preview/VixenPreview/Shapes/PreviewMovingHeadPartial.cs
src/Vixen.Modules/Preview/VixenPreview/VixenPreviewControl.cs

VIX-3517 Intelligent Fixture (Moving Head) Preview Shape continues to resize after the mouse has been released

 VIX-3517 Intelligent Fixture (Moving Head) Preview Shape continues to resize after the mouse has been released

---

src/Vixen.Modules/Preview/VixenPreview/Shapes/PreviewMovingHead.cs
src/Vixen.Modules/Preview/VixenPreview/Shapes/PreviewMovingHeadPartial.cs
src/Vixen.Modules/Preview/VixenPreview/VixenPreviewControl.cs

VIX-3516 Intelligent Fixture (Moving Head) does not draw immediately in preview setup
** NOTE ** - This branch is based off VIX-3517 so please process that pull request first.

VIX-3516 Intelligent Fixture (Moving Head) does not draw immediately in preview setup

---

src/Vixen.Modules/Editor/TimedSequenceEditor/MarkCollectionImportDialog.Designer.cs

VIX-3138 Resized mark import dialog.

---

src/Vixen.Modules/Controller/E131/SetupForm.Designer.cs
src/Vixen.Modules/Controller/E131/SetupForm.cs

Added a delete all button to the sACN e1.31 controller setup form.

VIX-3111 Add delete all universes button to sACN E1.31 form.

---

src/Vixen.Modules/Controller/E131/UnicastForm.Designer.cs
src/Vixen.Modules/Controller/E131/UnicastForm.resx

Add icon to unicast destination form

VIX-3104 Add icon to unicast destination form

---

src/Vixen.Modules/Effect/Shockwave/Shockwave.cs
src/Vixen.Modules/Effect/Shockwave/ShockwaveData.cs
src/Vixen.Modules/Effect/Shockwave/Shockwave_Diamond.cs
src/Vixen.Modules/EffectEditor/EffectDescriptorAttributes/EffectDescriptionDescriptors.resx
src/Vixen.Modules/EffectEditor/EffectDescriptorAttributes/EffectDisplayNameDescriptors.resx

VIX-3505 Add Diamond Shape to Shockwave Effect

VIX-3505 Add Diamond Shape to Shockwave Effect

---

src/Vixen.Modules/Controller/E131/SetupForm.cs

If a user deleted the last universe and then tried to close the form,Vixen would crash, this prevents that.

VIX-3526 Added logic to enable\disable delete universe button

---

src/Vixen.Modules/Effect/Effect/FixtureEffectBase.cs

VIX-3533 Fixing Intelligent Fixture Index Intent Generation with Ranges

VIX-3533 Fixing Intelligent Fixture Index Intent Generation with Ranges

---

src/Vixen.Modules/LayerMixingFilter/MaskFill/MaskAndFillSetup.Designer.cs
src/Vixen.Modules/LayerMixingFilter/MaskFill/MaskAndFillSetup.cs
src/Vixen.Modules/LayerMixingFilter/MaskFill/MaskAndFillSetup.resx

This is on the mask and fill configuration form.

VIX-3132 Added icon and removed extra buttons

---

src/Vixen.Core/Commands/Named8BitCommand.cs
src/Vixen.Modules/Editor/FixtureGraphics/IMovingHead.cs
src/Vixen.Modules/Editor/FixtureGraphics/MovingHeadSettings.cs
src/Vixen.Modules/Effect/Effect/FixtureEffectBase.cs
src/Vixen.Modules/Preview/VixenPreview/OpenGL/OpenGLPreviewForm.cs
src/Vixen.Modules/Preview/VixenPreview/Shapes/IOpenGLMovingHeadShape.cs
src/Vixen.Modules/Preview/VixenPreview/Shapes/MovingHeadIntentHandler.cs
src/Vixen.Modules/Preview/VixenPreview/Shapes/MovingHeadTimer.cs
src/Vixen.Modules/Preview/VixenPreview/Shapes/PreviewMovingHead.cs
src/Vixen.Modules/Preview/VixenPreview/Shapes/PreviewMovingHeadPartial.cs

Please merge VIX-3533 before merging this request.

VIX-3519 Set strobe min and max rates

---

src/Vixen.Modules/EffectEditor/EffectDescriptorAttributes/EffectDescriptionDescriptors.resx

VIX-3505 Fixing Shockwave Diamond Tooltip

VIX-3505 Fixing Shockwave Diamond Tooltip

---

src/Vixen.Modules/Effect/SetPosition/SetPositionData.cs
src/Vixen.Modules/Effect/SetPosition/SetPositionModule.cs
src/Vixen.Modules/EffectEditor/EffectDescriptorAttributes/EffectDescriptionDescriptors.resx
src/Vixen.Modules/EffectEditor/EffectDescriptorAttributes/EffectDisplayNameDescriptors.resx
src/Vixen.Modules/Sequence/Timed/Timed.csproj
src/Vixen.Modules/Sequence/Timed/TimedSequenceDescriptor.cs
src/Vixen.Modules/Sequence/Timed/TimedSequenceMigrator.cs

VIX-3510 Control pan and tilt separately as option
This branch is based off of VIX-3505 so please merge that pull request first and maybe we avoid a conflict and rebase.

VIX-3510 Control pan and tilt separately as option

---

src/Vixen.Core/Commands/Named8BitCommand.cs
src/Vixen.Modules/Editor/FixtureGraphics/IMovingHead.cs
src/Vixen.Modules/Editor/FixtureGraphics/MovingHeadSettings.cs
src/Vixen.Modules/Effect/Effect/FixtureEffectBase.cs
src/Vixen.Modules/Preview/VixenPreview/OpenGL/OpenGLPreviewForm.cs
src/Vixen.Modules/Preview/VixenPreview/Shapes/IOpenGLMovingHeadShape.cs
src/Vixen.Modules/Preview/VixenPreview/Shapes/MovingHeadIntentHandler.cs
src/Vixen.Modules/Preview/VixenPreview/Shapes/MovingHeadTimer.cs
src/Vixen.Modules/Preview/VixenPreview/Shapes/PreviewMovingHead.cs
src/Vixen.Modules/Preview/VixenPreview/Shapes/PreviewMovingHeadPartial.cs
src/Vixen.Modules/Preview/VixenPreview/VixenPreviewControl.cs

VIX-3524 Create pan and tilt max speeds
This branch is based off VIX-3513.  Please process after VIX-3513.

VIX-3524 Create pan and tilt max speeds

---

src/Vixen.Core/Commands/Named8BitCommand.cs
src/Vixen.Modules/Editor/FixtureGraphics/IMovingHead.cs
src/Vixen.Modules/Editor/FixtureGraphics/MovingHeadSettings.cs
src/Vixen.Modules/Effect/Effect/FixtureEffectBase.cs
src/Vixen.Modules/Preview/VixenPreview/OpenGL/OpenGLPreviewForm.cs
src/Vixen.Modules/Preview/VixenPreview/Shapes/IOpenGLMovingHeadShape.cs
src/Vixen.Modules/Preview/VixenPreview/Shapes/MovingHeadIntentHandler.cs
src/Vixen.Modules/Preview/VixenPreview/Shapes/MovingHeadTimer.cs
src/Vixen.Modules/Preview/VixenPreview/Shapes/PreviewMovingHead.cs
src/Vixen.Modules/Preview/VixenPreview/Shapes/PreviewMovingHeadPartial.cs
src/Vixen.Modules/Preview/VixenPreview/VixenPreviewControl.cs

VIX-3520 Set spin color wheel min and max rates
This branch was based off of VIX-3524.  Please merge that pull request first.

VIX-3520 Set spin color wheel min and max rates

---

src/Vixen.Modules/Editor/FixtureWizard/Wizard/ViewModels/EditProfileWizardPageViewModel.cs
src/Vixen.Modules/Editor/FixtureWizard/Wizard/ViewModels/GroupingWizardPageViewModel.cs

VIX-3275 Default the Fixture Element Name to the Profile Name

VIX-3275 Default the Fixture Element Name to the Profile Name

---

src/Vixen.Modules/Editor/FixtureGraphics/IMovingHead.cs
src/Vixen.Modules/Editor/FixtureGraphics/MovingHeadSettings.cs
src/Vixen.Modules/Preview/VixenPreview/OpenGL/OpenGLPreviewForm.cs
src/Vixen.Modules/Preview/VixenPreview/Shapes/IOpenGLMovingHeadShape.cs
src/Vixen.Modules/Preview/VixenPreview/Shapes/MovingHeadIntentHandler.cs
src/Vixen.Modules/Preview/VixenPreview/Shapes/PreviewMovingHead.cs
src/Vixen.Modules/Preview/VixenPreview/Shapes/PreviewMovingHeadPartial.cs
src/Vixen.Modules/Preview/VixenPreview/VixenPreviewControl.cs

VIX-3535 Removing internal flag from the Moving Head Preview properties
This branch was created off of VIX-3520.  So please process VIX-3520 before processing this pull request.

VIX-3535 Removing internal flag from the Moving Head Preview properties

---

src/Vixen.Modules/Editor/FixtureGraphics/IMovingHead.cs
src/Vixen.Modules/Editor/FixtureGraphics/MovingHeadSettings.cs
src/Vixen.Modules/Preview/VixenPreview/OpenGL/OpenGLPreviewForm.cs
src/Vixen.Modules/Preview/VixenPreview/Shapes/IOpenGLMovingHeadShape.cs
src/Vixen.Modules/Preview/VixenPreview/Shapes/MovingHeadIntentHandler.cs
src/Vixen.Modules/Preview/VixenPreview/Shapes/PreviewMovingHead.cs
src/Vixen.Modules/Preview/VixenPreview/Shapes/PreviewMovingHeadPartial.cs
src/Vixen.Modules/Preview/VixenPreview/VixenPreviewControl.cs

VIX-3537 Add additional property categories for fixtures
This branch is based off of VIX-3535.  Please process VIX-3535 before merging this pull request.

VIX-3537 Add additional property categories for fixtures

---

src/Vixen.Modules/Preview/VixenPreview/Shapes/PreviewMovingHead.cs

VIX-3543 Fixture selection indicator is offset on some different zoom levels

VIX-3543 Fixture selection indicator is offset on some different zoom levels

---

src/Vixen.Modules/Preview/VixenPreview/Shapes/PreviewMovingHeadPartial.cs

VIX-3547 Intelligent Fixture Preview Properties are not properly defaulted

VIX-3547 Intelligent Fixture Preview Properties are not properly defaulted

---

src/Vixen.Modules/Effect/Border/Border.cs
src/Vixen.Modules/Effect/Border/BorderData.cs
src/Vixen.Modules/Effect/Border/BorderMode.cs
src/Vixen.Modules/Effect/Border/RenderLevel.cs
src/Vixen.Modules/EffectEditor/EffectDescriptorAttributes/EffectDescriptionDescriptors.resx
src/Vixen.Modules/EffectEditor/EffectDescriptorAttributes/EffectDisplayNameDescriptors.resx

VIX-3406 Add Marquee Effect

---

src/Vixen.Modules/Effect/Whirlpool/Whirlpool/Whirlpool.cs

VIX-3549 Fixing Whirlpool Help Link

VIX-3549 Fixing Whirlpool Help Link

---

src/Vixen.Modules/Effect/Border/Border.cs

VIX-3550 Fixing movement with Render Level 1 or 2

VIX-3550 Fixing movement with Render Level 1 or 2

---

src/Vixen.Modules/Editor/FixtureGraphics/OpenGL/MovingHeadOpenGL.cs

VIX-3569 Moving Head Beam Preview Transparency is getting reset to full intensity

VIX-3569 Moving Head Beam Preview Transparency is getting reset to full intensity

---

src/Vixen.Modules/Preview/VixenPreview/OpenGL/OpenGLPreviewForm.cs

VIX-2966 Add Center Preview Context Menu to OpenGL Preview

VIX-2966 Add Center Preview Context Menu to OpenGL Preview

---

src/Vixen.Modules/App/Curves/ZedGraph/PointPairList.cs

VIX-3585 Fixing interpolation bug when consecutive points have the same Y value

VIX-3585 Fixing interpolation bug when consecutive points have the same Y value

---

src/Vixen.Modules/Effect/LineDance/LineDanceModule.cs

VIX-3586 Fixing Odd Number of Moving Heads Logic

VIX-3586 Fixing Odd Number of Moving Heads Logic

---

src/Vixen.Modules/Effect/LineDance/LineDanceModule.cs

VIX-3587 Fixing Line Dance Effect Help Link

VIX-3587 Fixing Line Dance Effect Help Link

---

src/Vixen.Application/VixenApplication.cs

VIX-3608 Fixing more resource leaks

VIX-3608 Fixing more resource leaks

---

src/Vixen.Modules/Editor/TimedSequenceEditor/TimedSequenceEditorForm_ContextMenu.cs
src/Vixen.Modules/Editor/TimedSequenceEditor/TimedSequenceEditorForm_Hotkeys.cs

1) All Alignment tools now have quick keys
2) The quick key descriptions are consistent in how they are showing
Also updated documentation to reflect these changes.

VIX-3616 Update/Add Quickkeys for Alignment tool

---

src/Vixen.Modules/Editor/TimedSequenceEditor/TimedSequenceEditorForm.cs

Corrected a math error where a time calculation was the using the current seconds (sometimes 0) as a duration instead of the TOTAL seconds.

VIX-3582 Revised how a duration was calculated

---

src/Vixen.Common/Controls/TimeLineControl/Element.cs
src/Vixen.Common/Controls/TimeLineControl/Grid.cs
src/Vixen.Common/Controls/TimeLineControl/Grid_Mouse.cs
src/Vixen.Common/Controls/TimeLineControl/Row.cs

Added Alt + Shift key control to adjoin only Effects at the same Layer.

VIX-2615 Updated design to accommodate adjoining effects only at the same Layer.

---

src/Vixen.Modules/Effect/Candle/CandleModule.cs
src/Vixen.Modules/Effect/Chase/Chase.cs
src/Vixen.Modules/Effect/Dissolve/Dissolve.cs
src/Vixen.Modules/Effect/SetLevel/SetLevel.cs
src/Vixen.Modules/Effect/Spin/Spin.cs
src/Vixen.Modules/Effect/Strobe/Strobe.cs

This is an amendment to the original PR adding the remaining basic effects.

VIX-3631 Fix remaining basic effects to prevent duplicate node rendering.

---

src/Vixen.Modules/Preview/VixenPreview/Shapes/PreviewSetElements.cs

Fixed spaces vs tabs formatting in a separate commit in the affected file.

VIX-3639 Fix issue with preview not updating on reverse of linked elements.

---

src/Vixen.Modules/Preview/VixenPreview/VixenPreviewModuleInstance.cs

* Replaced the use of GLControl with NativeWindow to test for OpenGL.
* Tweaked some of the logging messages to be more concise.

VIX-3623 Fix issue with testing for OpenGL support

---

src/Vixen.Modules/Controller/ElexolEtherIO/ElexolEtherIOModule.cs
src/Vixen.Modules/Controller/ElexolEtherIO/SetupDialog.Designer.cs
src/Vixen.Modules/Controller/ElexolEtherIO/SetupDialog.cs
src/Vixen.Modules/Controller/ElexolEtherIO/SetupDialog.resx

* Add settings to allow the Cancel button to return a DialogResult so it will work.
* Add exception handling logic to the network functions to ensure proper logging and handling should things go wrong.

VIX-3644 Fix crash issues in ElexolEtherIO controller

---

src/Vixen.Application/Setup/DisplaySetup.cs
src/Vixen.Application/Setup/ISetupPatchingControl.cs
src/Vixen.Application/Setup/SetupControllersSimple.cs
src/Vixen.Application/Setup/SetupPatchingGraphical.cs
src/Vixen.Application/Setup/SetupPatchingSimple.cs
src/Vixen.Common/Controls/ControllerTree.Designer.cs
src/Vixen.Common/Controls/ControllerTree.cs

Add context menu items to unpatch controllers/channels and find patched elements.

VIX-2356 Added context menus

---

src/Vixen.Application/Setup/SetupElementsTree.cs

Changed the default item to “Single Item” in the "Elements" pane of the "Setup Display" screen.

VIX-3333 Changed the default item to “Single Item” 

---

src/Vixen.Modules/Editor/TimedSequenceEditor/Forms/WPF/MarksDocker/ViewModels/MarkDockerViewModel.cs

Correct bug where clicking on Show Tail Marks icon doesn't select/deselect all lines.

VIX-3653 Correct bug for clicking on Show Tail Marks icon 

---

src/Vixen.Modules/Preview/VixenPreview/OpenGL/Constructs/Shaders/ShaderProgram.cs
src/Vixen.Modules/Preview/VixenPreview/OpenGL/OpenGLPreviewForm.cs
src/Vixen.Modules/Preview/VixenPreview/Shapes/PreviewLightBaseShape.cs

VIX-3067 Improving OpenGL Drawing Performance

VIX-3067 Improving OpenGL Drawing Performance

---

src/Vixen.Common/Controls/TimeLineControl/Grid.cs
src/Vixen.Common/Controls/TimeLineControl/LabeledMarks/MarksBulkChangeInfo.cs
src/Vixen.Common/Controls/TimeLineControl/TimelineControlBase.cs
src/Vixen.Core/Marks/IMarkCollection.cs
src/Vixen.Modules/App/Marks/Mark.cs
src/Vixen.Modules/App/Marks/MarkCollection.cs
src/Vixen.Modules/Editor/TimedSequenceEditor/BulkEffectMoveForm.Designer.cs
src/Vixen.Modules/Editor/TimedSequenceEditor/BulkEffectMoveForm.cs
src/Vixen.Modules/Editor/TimedSequenceEditor/TimedSequenceEditorForm.cs
src/Vixen.Modules/Editor/TimedSequenceEditor/TimedSequenceEditorForm_Menu.cs
src/Vixen.Modules/Editor/TimedSequenceEditor/Undo/MarksBulkChangeUndoAction.cs

1) Include Marks in bulk move
2) Clip Effects/Marks that are moved beyond the range of the Sequence

VIX-3269 Added options to Bulk Move Effects dialog

---

src/Vixen.Core/Sys/Props/BaseProp.cs
src/Vixen.Core/Sys/Props/Model/BaseLightModel.cs
src/Vixen.Core/Sys/Props/Model/BasePropModel.cs
src/Vixen.Modules/App/Props/Models/Arch/Arch.cs
src/Vixen.Modules/App/Props/Models/BaseLightProp.cs
src/Vixen.Modules/App/Props/Models/Tree/Tree.cs

Moving logic into the base classes for the Prop and PropModel

VIX-3720 Moving logic into the base classes for the Prop and PropModel
